"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabaseClient";
import { HRAccessGuard, HRNavigation } from "@/app/components/hr";

type Item = { id:string; request_id:string; officer_id:string; section_key:string; status:string; priority:string; due_at:string|null; officer_recommendation:string|null; submitted_at:string|null; requests?:{request_no?:string|null;title?:string|null;current_stage?:string|null;status?:string|null}|null };
type Officer = { id:string; full_name:string|null; email:string|null };
const title = (v:string) => v.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function HRReviewPage(){
 const [items,setItems]=useState<Item[]>([]); const [officers,setOfficers]=useState<Officer[]>([]); const [comment,setComment]=useState<Record<string,string>>({}); const [message,setMessage]=useState("");
 async function load(){ const [{data:i,error},{data:o}] = await Promise.all([supabase.from("hr_request_assignments").select("id,request_id,officer_id,section_key,status,priority,due_at,officer_recommendation,submitted_at,requests(request_no,title,current_stage,status)").in("status",["submitted","returned","approved"]).order("submitted_at",{ascending:false}),supabase.from("profiles").select("id,full_name,email")]); setItems((i||[]) as unknown as Item[]); setOfficers((o||[]) as Officer[]); setMessage(error?.message||""); }
 useEffect(()=>{load();},[]); const names=useMemo(()=>new Map(officers.map(o=>[o.id,o.full_name||o.email||o.id])),[officers]);
 async function decide(item:Item,decision:"approved"|"returned"|"completed") { const {data:auth}=await supabase.auth.getUser(); const note=comment[item.id]||""; const {error}=await supabase.from("hr_request_assignments").update({status:decision,boss_comment:note,reviewed_by:auth.user?.id,reviewed_at:new Date().toISOString(),completed_at:decision==="completed"?new Date().toISOString():null}).eq("id",item.id); if(!error) await supabase.from("hr_request_reviews").insert({assignment_id:item.id,request_id:item.request_id,officer_id:item.officer_id,reviewed_by:auth.user?.id,decision,comment:note}); setMessage(error?.message||""); load(); }
 return <HRAccessGuard bossOnly><main className="min-h-screen bg-slate-50 px-4 py-8 lg:px-8"><div className="mx-auto max-w-7xl space-y-6"><section className="rounded-[2rem] bg-gradient-to-br from-amber-950 via-orange-800 to-rose-700 p-8 text-white shadow-xl"><p className="text-xs font-black uppercase tracking-[.25em] text-amber-200">HR Boss Authority</p><h1 className="mt-3 text-3xl font-black lg:text-5xl">HR Review Queue</h1><p className="mt-3 max-w-3xl font-semibold text-orange-100">Review officers’ work, return it for correction, approve the HR assessment or close the HR stage before onward workflow.</p></section><HRNavigation />{message&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 font-bold text-red-700">{message}</div>}<section className="grid gap-4">{items.length===0?<div className="rounded-3xl bg-white p-10 text-center font-bold text-slate-500 shadow-sm">Nothing is awaiting HR Boss review.</div>:items.map(item=><article key={item.id} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 lg:flex-row"><div><p className="text-xs font-black uppercase tracking-widest text-orange-700">{title(item.section_key)} · {title(item.status)}</p><h2 className="mt-2 text-xl font-black text-slate-950">{item.requests?.request_no||item.request_id} — {item.requests?.title||"HR-bound request"}</h2><p className="mt-2 font-semibold text-slate-600">Assigned officer: {names.get(item.officer_id)||item.officer_id}</p>{item.officer_recommendation&&<div className="mt-4 rounded-2xl bg-blue-50 p-4 text-sm font-semibold text-blue-950">{item.officer_recommendation}</div>}</div><Link href={`/requests/${item.request_id}`} className="h-fit rounded-xl bg-blue-700 px-4 py-3 text-center font-extrabold text-white">Open Request</Link></div><textarea value={comment[item.id]||""} onChange={e=>setComment({...comment,[item.id]:e.target.value})} placeholder="HR Boss review comment" className="mt-5 min-h-24 w-full rounded-2xl border border-slate-300 p-4 font-medium outline-none focus:border-orange-500"/><div className="mt-4 flex flex-wrap gap-3"><button onClick={()=>decide(item,"returned")} className="rounded-xl bg-red-600 px-5 py-3 font-extrabold text-white">Return for Correction</button><button onClick={()=>decide(item,"approved")} className="rounded-xl bg-emerald-600 px-5 py-3 font-extrabold text-white">Approve Assessment</button><button onClick={()=>decide(item,"completed")} className="rounded-xl bg-violet-600 px-5 py-3 font-extrabold text-white">Complete HR Stage</button></div></article>)}</section></div></main></HRAccessGuard>;
}
