"use client";

import Image from "next/image";
import type { ReactNode } from "react";

export type PrintColumn = { key: string; label: string; align?: "left" | "center" | "right" };
export type PrintSummary = { label: string; value: string | number };

export default function EnterprisePrintDocument({
  title,
  subtitle,
  documentId,
  period,
  printedBy,
  activeRole,
  department,
  confidentiality = "INTERNAL USE",
  orientation = "portrait",
  summaries = [],
  columns,
  rows,
  observations,
  recommendations,
  children,
}: {
  title: string;
  subtitle?: string;
  documentId: string;
  period?: string;
  printedBy: string;
  activeRole: string;
  department?: string;
  confidentiality?: string;
  orientation?: "portrait" | "landscape";
  summaries?: PrintSummary[];
  columns?: PrintColumn[];
  rows?: Array<Record<string, unknown>>;
  observations?: string[];
  recommendations?: string[];
  children?: ReactNode;
}) {
  const generated = new Date();
  return (
    <article className={`iet-print-document iet-print-${orientation}`}>
      <header className="iet-print-header">
        <div className="iet-print-brand">
          <Image src="/iet-logo.png" alt="Islamic Education Trust" width={72} height={72} priority />
          <div>
            <div className="iet-print-org">ISLAMIC EDUCATION TRUST (IET)</div>
            <div className="iet-print-system">REQGEN ENTERPRISE PLATFORM</div>
            <div className="iet-print-address">Official Institutional Report</div>
          </div>
        </div>
        <div className="iet-print-meta">
          <div><b>Document ID:</b> {documentId}</div>
          <div><b>Generated:</b> {generated.toLocaleString("en-NG")}</div>
          <div><b>Printed by:</b> {printedBy}</div>
          <div><b>Active role:</b> {activeRole}</div>
          {department ? <div><b>Department:</b> {department}</div> : null}
          {period ? <div><b>Period:</b> {period}</div> : null}
        </div>
      </header>

      <section className="iet-print-title-block">
        <h1>{title}</h1>
        {subtitle ? <p>{subtitle}</p> : null}
      </section>

      {summaries.length ? (
        <section className="iet-print-summary-grid">
          {summaries.map((item) => (
            <div key={item.label} className="iet-print-summary-card">
              <span>{item.label}</span><strong>{item.value}</strong>
            </div>
          ))}
        </section>
      ) : null}

      {children}

      {columns && rows ? (
        <section className="iet-print-section">
          <table className="iet-print-table">
            <thead><tr>{columns.map((column) => <th key={column.key} style={{ textAlign: column.align ?? "left" }}>{column.label}</th>)}</tr></thead>
            <tbody>
              {rows.length ? rows.map((row, index) => (
                <tr key={String(row.id ?? index)}>{columns.map((column) => <td key={column.key} style={{ textAlign: column.align ?? "left" }}>{String(row[column.key] ?? "—")}</td>)}</tr>
              )) : <tr><td colSpan={columns.length} className="iet-print-empty">No records available for the selected report.</td></tr>}
            </tbody>
          </table>
        </section>
      ) : null}

      {(observations?.length || recommendations?.length) ? (
        <section className="iet-print-notes-grid">
          {observations?.length ? <div><h2>Management Observations</h2><ol>{observations.map((item) => <li key={item}>{item}</li>)}</ol></div> : null}
          {recommendations?.length ? <div><h2>Recommendations</h2><ol>{recommendations.map((item) => <li key={item}>{item}</li>)}</ol></div> : null}
        </section>
      ) : null}

      <section className="iet-print-signatures">
        <div><span>Prepared By</span><b>{printedBy}</b></div>
        <div><span>Reviewed By</span><b>________________________</b></div>
        <div><span>Approved By</span><b>________________________</b></div>
      </section>

      <footer className="iet-print-footer">
        <span>Generated by ReqGen</span>
        <span>{confidentiality}</span>
        <span className="iet-page-number">Page</span>
      </footer>
    </article>
  );
}
