"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Archive, CalendarDays, Download, RotateCcw, Search, ShieldCheck } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
import styles from "@/app/registry/archive/archive.module.css";

type Raw=Record<string,unknown>; type Dept={id:string;name:string};
type Row={id:string;referenceNo:string;subject:string;direction:string;party:string;departmentId:string;department:string;archivedAt:string;retentionCategory:string;retentionUntil:string;location:string;archivedBy:string;status:string;createdAt:string};
function s(v:unknown,f=""){return typeof v==="string"&&v.trim()?v.trim():f;} function d(v:string){const x=new Date(v);return Number.isNaN(x.getTime())?null:x;} function dt(v:string){const x=d(v);return x?x.toLocaleString(undefined,{year:"numeric",month:"short",day:"2-digit",hour:"2-digit",minute:"2-digit"}):"—";} function day(v:string){const x=d(v);return x?x.toLocaleDateString(undefined,{year:"numeric",month:"short",day:"2-digit"}):"—";}
function mapRow(r:Raw,names:Map<string,string>):Row{const dep=s(r.department_id,s(r.dept_id));return{id:s(r.id),referenceNo:s(r.reference_no,"Unnumbered"),subject:s(r.subject,"Untitled correspondence"),direction:s(r.direction,"Incoming"),party:s(r.from_to,s(r.sender_name,s(r.recipient_name,s(r.sender,s(r.recipient,"—"))))),departmentId:dep,department:s(r.department_name,names.get(dep)||"Unassigned"),archivedAt:s(r.archived_at,s(r.updated_at,s(r.created_at))),retentionCategory:s(r.retention_category,"General Correspondence"),retentionUntil:s(r.retention_until,s(r.retention_date)),location:s(r.archive_location,s(r.storage_location,s(r.location,"—"))),archivedBy:s(r.archived_by_name,s(r.archived_by,"—")),status:s(r.archive_status,s(r.status,"Archived")),createdAt:s(r.created_at)}}
function archived(r:Raw){return /archive|retained|expired/i.test(`${s(r.status)} ${s(r.archive_status)}`)||!!s(r.archived_at);} function isThisMonth(v:string){const x=d(v),n=new Date();return !!x&&x.getFullYear()===n.getFullYear()&&x.getMonth()===n.getMonth();} function expired(v:string){const x=d(v);return !!x&&x.getTime()<Date.now();}
export default function RegistryArchiveWorkspace(){
 const [rows,setRows]=useState<Row[]>([]),[active,setActive]=useState<Row[]>([]),[departments,setDepartments]=useState<Dept[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState<string|null>(null),[showAdd,setShowAdd]=useState(false),[saving,setSaving]=useState(false);
 const [query,setQuery]=useState(""),[dateFrom,setDateFrom]=useState(""),[dateTo,setDateTo]=useState(""),[direction,setDirection]=useState("all"),[department,setDepartment]=useState("all"),[category,setCategory]=useState("all"),[status,setStatus]=useState("all"),[location,setLocation]=useState("all"),[archivedBy,setArchivedBy]=useState("all"),[selected,setSelected]=useState(""); const [page,setPage]=useState(1); const pageSize=10;
 const load=useCallback(async()=>{setLoading(true);setMessage(null);const [dr,rr]=await Promise.all([supabase.from("departments").select("id,name").order("name"),supabase.from("registry_correspondence").select("*").order("created_at",{ascending:false}).limit(3000)]); const depts=(dr.data||[]) as Dept[]; setDepartments(depts);const names=new Map(depts.map(x=>[x.id,x.name]));if(rr.error){setMessage(`Registry Archive: ${rr.error.message}`);setRows([]);setActive([]);}else{const raw=(rr.data||[]) as Raw[];setRows(raw.filter(archived).map(r=>mapRow(r,names)));setActive(raw.filter(r=>!archived(r)).map(r=>mapRow(r,names)));}setLoading(false);},[]);
 useEffect(()=>{queueMicrotask(()=>{void load();});},[load]);
 const categories=useMemo(()=>Array.from(new Set(rows.map(r=>r.retentionCategory))).filter(Boolean).sort(),[rows]); const statuses=useMemo(()=>Array.from(new Set(rows.map(r=>r.status))).filter(Boolean).sort(),[rows]); const locations=useMemo(()=>Array.from(new Set(rows.map(r=>r.location))).filter(x=>x&&x!=="—").sort(),[rows]); const archivists=useMemo(()=>Array.from(new Set(rows.map(r=>r.archivedBy))).filter(x=>x&&x!=="—").sort(),[rows]);
 const filtered=useMemo(()=>rows.filter(r=>{const q=query.trim().toLowerCase();const a=d(r.archivedAt);return(!q||[r.referenceNo,r.subject,r.party,r.department].some(x=>x.toLowerCase().includes(q)))&&(direction==="all"||r.direction.toLowerCase()===direction)&&(department==="all"||r.departmentId===department)&&(category==="all"||r.retentionCategory===category)&&(status==="all"||r.status===status)&&(location==="all"||r.location===location)&&(archivedBy==="all"||r.archivedBy===archivedBy)&&(!dateFrom||!!a&&a>=new Date(`${dateFrom}T00:00:00`))&&(!dateTo||!!a&&a<=new Date(`${dateTo}T23:59:59`));}),[rows,query,direction,department,category,status,location,archivedBy,dateFrom,dateTo]);
 const pc=Math.max(1,Math.ceil(filtered.length/pageSize)),safePage=Math.min(page,pc),paged=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
 const stats=useMemo(()=>{const year=new Date().getFullYear();return{total:rows.length,month:rows.filter(r=>isThisMonth(r.archivedAt)).length,incoming:rows.filter(r=>r.direction.toLowerCase()==="incoming").length,outgoing:rows.filter(r=>r.direction.toLowerCase()==="outgoing").length,overdue:rows.filter(r=>r.retentionUntil&&expired(r.retentionUntil)&&!/disposed/i.test(r.status)).length,restored:rows.filter(r=>/restored/i.test(r.status)&&d(r.archivedAt)?.getFullYear()===year).length};},[rows]);
 async function archiveSelected(){if(!selected)return;setSaving(true);setMessage(null);const now=new Date().toISOString();let result=await supabase.from("registry_correspondence").update({status:"Archived",archived_at:now}).eq("id",selected);if(result.error&&/column|archived_at|schema/i.test(result.error.message))result=await supabase.from("registry_correspondence").update({status:"Archived"}).eq("id",selected);if(result.error)setMessage(`Unable to archive record: ${result.error.message}`);else{setMessage("Record added to Registry Archive.");setSelected("");setShowAdd(false);await load();}setSaving(false);}
 async function restore(id:string){if(!window.confirm("Restore this archived correspondence to the active Registry?"))return;setMessage(null);let result=await supabase.from("registry_correspondence").update({status:"Restored",restored_at:new Date().toISOString()}).eq("id",id);if(result.error&&/column|restored_at|schema/i.test(result.error.message))result=await supabase.from("registry_correspondence").update({status:"Restored"}).eq("id",id);if(result.error)setMessage(`Unable to restore record: ${result.error.message}`);else{setMessage("Archived record restored successfully.");await load();}}
 function exportCsv(){const head=["Reference","Subject","Direction","From/To","Department","Archived Date","Retention Category","Retention Until","Location","Archived By","Status"];const lines=[head,...filtered.map(r=>[r.referenceNo,r.subject,r.direction,r.party,r.department,r.archivedAt,r.retentionCategory,r.retentionUntil,r.location,r.archivedBy,r.status])].map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const blob=new Blob([lines],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`registry-archive-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);}
 return <main className={styles.page}><div className={styles.shell}><section className={styles.hero}><div><div className={styles.breadcrumb}>Home › Registry › Registry Archive</div><h1 className={styles.title}>Registry Archive</h1><p className={styles.subtitle}>View and manage archived correspondence records. Restore records only when there is an authorised business need.</p></div><div className={styles.actions}><button className={styles.secondary} onClick={()=>window.print()}><ShieldCheck size={16}/>Retention Policy</button><button className={styles.secondary} onClick={exportCsv}><Download size={16}/>Export Archive Report</button><button className={styles.button} onClick={()=>setShowAdd(v=>!v)}><Archive size={16}/>{showAdd?"Close":"Add to Archive"}</button></div></section>
 {message&&<div className={`${styles.notice} ${/unable/i.test(message)?styles.error:styles.success}`}>{message}</div>}
 <section className={styles.kpis}>{[["Total Archived",stats.total,"All archived records"],["Archived This Month",stats.month,"Current month"],["Incoming Archived",stats.incoming,"Incoming records"],["Outgoing Archived",stats.outgoing,"Outgoing records"],["Overdue Retention",stats.overdue,"Requires attention"],["Restored This Year",stats.restored,"Current year"]].map(x=><div className={styles.kpi} key={String(x[0])}><div className={styles.kpiLabel}>{String(x[0])}</div><div className={styles.kpiValue}>{loading?"—":Number(x[1]).toLocaleString()}</div><div className={styles.kpiNote}>{String(x[2])}</div></div>)}</section>
 {showAdd&&<section className={styles.archiveForm}><div><h2 className={styles.cardTitle}>Add Existing Correspondence to Archive</h2><p className={styles.cardNote}>Only active Registry records can be selected. Historical data remains in the same authoritative Registry source.</p></div><div className={styles.formGrid}><label className={styles.field}><span className={styles.label}>Correspondence</span><select className={styles.select} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select record...</option>{active.map(r=><option key={r.id} value={r.id}>{r.referenceNo} — {r.subject}</option>)}</select></label><div/><div style={{display:"flex",alignItems:"end"}}><button className={styles.button} disabled={!selected||saving} onClick={()=>void archiveSelected()}>{saving?"Archiving...":"Archive Record"}</button></div></div></section>}
 <section className={styles.card}><div className={styles.filters}><label className={styles.field}><span className={styles.label}>Search Archive</span><div style={{position:"relative"}}><Search size={15} style={{position:"absolute",left:12,top:14,color:"#70839c"}}/><input className={styles.input} style={{paddingLeft:34}} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Reference no., subject, sender/recipient..."/></div></label><label className={styles.field}><span className={styles.label}>Archive Date From</span><input type="date" className={styles.input} value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/></label><label className={styles.field}><span className={styles.label}>Archive Date To</span><input type="date" className={styles.input} value={dateTo} onChange={e=>setDateTo(e.target.value)}/></label><label className={styles.field}><span className={styles.label}>Direction</span><select className={styles.select} value={direction} onChange={e=>setDirection(e.target.value)}><option value="all">All Directions</option><option value="incoming">Incoming</option><option value="outgoing">Outgoing</option></select></label><label className={styles.field}><span className={styles.label}>Department</span><select className={styles.select} value={department} onChange={e=>setDepartment(e.target.value)}><option value="all">All Departments</option>{departments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className={styles.field}><span className={styles.label}>Retention Category</span><select className={styles.select} value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All Categories</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label></div><div className={styles.filters2}><label className={styles.field}><span className={styles.label}>Retained Status</span><select className={styles.select} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All Statuses</option>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label className={styles.field}><span className={styles.label}>Archive Location</span><select className={styles.select} value={location} onChange={e=>setLocation(e.target.value)}><option value="all">All Locations</option>{locations.map(x=><option key={x}>{x}</option>)}</select></label><label className={styles.field}><span className={styles.label}>Archived By</span><select className={styles.select} value={archivedBy} onChange={e=>setArchivedBy(e.target.value)}><option value="all">All Users</option>{archivists.map(x=><option key={x}>{x}</option>)}</select></label><div style={{display:"flex",alignItems:"end"}}><button className={styles.secondary} onClick={()=>{setQuery("");setDateFrom("");setDateTo("");setDirection("all");setDepartment("all");setCategory("all");setStatus("all");setLocation("all");setArchivedBy("all");}}><RotateCcw size={15}/>Reset Filters</button></div></div></section>
 <section className={styles.tableCard}><div className={styles.tableHead}><div><h2 className={styles.cardTitle}>Archived Correspondence</h2><p className={styles.cardNote}>{filtered.length.toLocaleString()} record(s)</p></div><span className={styles.badge} style={{background:"#eef5ff",color:"#1459b5"}}>{loading?"Loading...":`${filtered.length} records`}</span></div><div className={styles.tableWrap}>{paged.length?<table><thead><tr><th>Ref. No.</th><th>Subject</th><th>Direction</th><th>From / To</th><th>Department</th><th>Archived Date</th><th>Retention Category</th><th>Retention Until</th><th>Location / Reference</th><th>Archived By</th><th>Status</th><th>Actions</th></tr></thead><tbody>{paged.map(r=><tr key={r.id}><td className={styles.ref}>{r.referenceNo}</td><td>{r.subject}</td><td><span className={styles.badge} style={{background:r.direction.toLowerCase()==="incoming"?"#eef5ff":"#e9fbf3",color:r.direction.toLowerCase()==="incoming"?"#1459b5":"#087247"}}>{r.direction}</span></td><td>{r.party}</td><td>{r.department}</td><td>{dt(r.archivedAt)}</td><td>{r.retentionCategory}</td><td>{day(r.retentionUntil)}</td><td>{r.location}</td><td>{r.archivedBy}</td><td><span className={styles.badge} style={{background:expired(r.retentionUntil)?"#fff0f0":"#e9fbf3",color:expired(r.retentionUntil)?"#b4232f":"#087247"}}>{expired(r.retentionUntil)?"Expired":r.status}</span></td><td><button className={`${styles.action} ${styles.actionRestore}`} onClick={()=>void restore(r.id)}>Restore</button></td></tr>)}</tbody></table>:<div className={styles.empty}>{loading?"Loading Registry Archive...":"No archived correspondence matches the selected filters."}</div>}</div><div className={styles.pager}><span>Showing {paged.length?((safePage-1)*pageSize+1):0}–{Math.min(safePage*pageSize,filtered.length)} of {filtered.length}</span><div className={styles.pageBtns}>{Array.from({length:Math.min(pc,7)},(_,i)=>i+1).map(p=><button key={p} className={`${styles.pageBtn} ${p===safePage?styles.active:""}`} onClick={()=>setPage(p)}>{p}</button>)}</div></div></section>
 <section className={`${styles.card} ${styles.manage}`}><div><h2 className={styles.cardTitle}>Archive Management</h2><p className={styles.cardNote}>Archived records are preserved according to their retention category. Restore records only when an authorised business need exists. Permanent disposal should remain a separately authorised records-management action.</p></div><div className={styles.guide}><div className={styles.guideRow}><RotateCcw size={18} color="#0a8755"/><span><strong>Restore:</strong> Bring an archived record back to the active Registry.</span></div><div className={styles.guideRow}><Archive size={18} color="#1263f3"/><span><strong>Retention:</strong> Keep records for the required organisational period.</span></div><div className={styles.guideRow}><CalendarDays size={18} color="#d97706"/><span><strong>Review:</strong> Expired retention requires authorised records review before disposal.</span></div></div></section>
 </div></main>;
}
