"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { supabase } from "@/lib/supabaseClient";
import { ActionButton, EmptyState, EnterpriseHero, EnterpriseShell, SectionCard, StatCard, StatusBadge } from "@/app/components/enterprise/EnterpriseUI";
import { dateText, normalizeRows, text } from "@/app/components/enterprise/data";

type Tab = "overview" | "incoming" | "outgoing" | "dispatch" | "all";
type Item = { id:string; referenceNo:string; subject:string; department:string; status:string; priority:string; direction:string; createdAt:string; sender:string; recipient:string; dispatchMethod:string };
const tabs: Array<{key:Tab; label:string}> = [{key:"overview",label:"Overview"},{key:"incoming",label:"Incoming"},{key:"outgoing",label:"Outgoing"},{key:"dispatch",label:"Dispatch"},{key:"all",label:"All Operations"}];
function badgeTone(value:string){ const s=value.toLowerCase(); if(/complete|delivered|collected|archived/.test(s)) return "emerald" as const; if(/overdue|missing|reject|cancel/.test(s)) return "rose" as const; if(/pending|awaiting|draft/.test(s)) return "amber" as const; return "blue" as const; }

export default function RegistryCentre(){
 const params=useSearchParams(); const requested=params.get("tab") as Tab | null;
 const [tab,setTab]=useState<Tab>(tabs.some(x=>x.key===requested)?requested!:"overview"); const [rows,setRows]=useState<Item[]>([]); const [loading,setLoading]=useState(true); const [warning,setWarning]=useState<string|null>(null); const [query,setQuery]=useState(""); const [status,setStatus]=useState("all"); const [department,setDepartment]=useState("all");
 const load=useCallback(async()=>{ setLoading(true); setWarning(null); const result=await supabase.from("registry_correspondence").select("*").order("created_at",{ascending:false}).limit(1000); if(result.error){ setWarning("Registry correspondence is unavailable to this active role or the operational table is not ready."); setRows([]); } else setRows(normalizeRows(result.data).map(r=>({id:text(r.id),referenceNo:text(r.reference_no,"Unnumbered"),subject:text(r.subject,"Untitled correspondence"),department:text(r.department_name,text(r.department_id,"Unassigned")),status:text(r.status,"Pending"),priority:text(r.priority,"Normal"),direction:text(r.direction,"Incoming"),createdAt:text(r.created_at),sender:text(r.sender_name,text(r.sender,"—")),recipient:text(r.recipient_name,text(r.recipient,"—")),dispatchMethod:text(r.dispatch_method,"—")}))); setLoading(false); },[]);
 useEffect(()=>{queueMicrotask(()=>void load())},[load]);
 const scoped=useMemo(()=>rows.filter(r=>tab==="overview"||tab==="all"||(tab==="incoming"&&r.direction.toLowerCase()==="incoming")||(tab==="outgoing"&&r.direction.toLowerCase()==="outgoing")||(tab==="dispatch"&&/dispatch|collection|delivered|awaiting/i.test(r.status))),[rows,tab]);
 const departments=useMemo(()=>Array.from(new Set(rows.map(r=>r.department).filter(Boolean))).sort(),[rows]);
 const statuses=useMemo(()=>Array.from(new Set(rows.map(r=>r.status).filter(Boolean))).sort(),[rows]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase(); return scoped.filter(r=>(department==="all"||r.department===department)&&(status==="all"||r.status===status)&&(!q||[r.referenceNo,r.subject,r.department,r.status,r.priority,r.sender,r.recipient].some(v=>v.toLowerCase().includes(q))))},[scoped,query,status,department]);
 const stats=useMemo(()=>({total:rows.length,incoming:rows.filter(r=>r.direction.toLowerCase()==="incoming").length,outgoing:rows.filter(r=>r.direction.toLowerCase()==="outgoing").length,pending:rows.filter(r=>/pending|awaiting|draft/i.test(r.status)).length,urgent:rows.filter(r=>/urgent|high/i.test(r.priority)).length}),[rows]);
 return <EnterpriseShell><div className="mx-auto max-w-[1500px] space-y-4">
  <EnterpriseHero eyebrow="Registry" title="Registry Centre" description="One controlled workspace for incoming and outgoing correspondence, dispatch, collection and movement records." actions={<ActionButton tone="cyan" onClick={()=>void load()}>{loading?"Refreshing...":"Refresh Registry"}</ActionButton>}/>
  {warning?<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900">{warning}</div>:null}
  <div className="flex flex-wrap gap-2 rounded-xl border border-slate-200 bg-white p-2">{tabs.map(x=><button key={x.key} onClick={()=>setTab(x.key)} className={`rounded-lg px-4 py-2 text-[13px] font-black transition ${tab===x.key?"bg-blue-700 text-white":"text-slate-700 hover:bg-blue-50 hover:text-blue-700"}`}>{x.label}</button>)}</div>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Total Records" value={loading?"—":stats.total} note="Live correspondence" tone="blue"/><StatCard label="Incoming" value={loading?"—":stats.incoming} note="Received records" tone="cyan"/><StatCard label="Outgoing" value={loading?"—":stats.outgoing} note="Issued records" tone="violet"/><StatCard label="Pending Movement" value={loading?"—":stats.pending} note="Awaiting action" tone="amber"/><StatCard label="Urgent / High" value={loading?"—":stats.urgent} note="Priority attention" tone="rose"/></section>
  {tab==="overview"?<section className="grid gap-4 lg:grid-cols-2"><SectionCard title="Correspondence Direction" eyebrow="Live distribution"><div className="space-y-4"><Metric label="Incoming" value={stats.incoming} total={Math.max(stats.total,1)}/><Metric label="Outgoing" value={stats.outgoing} total={Math.max(stats.total,1)}/></div></SectionCard><SectionCard title="Registry Attention" eyebrow="Operational exceptions">{stats.total===0?<EmptyState title="No registry data yet" description="Charts and indicators remain empty until authorised Registry records exist."/>:<div className="grid gap-3 sm:grid-cols-2"><StatCard label="Pending" value={stats.pending} note="Needs movement/action" tone="amber"/><StatCard label="Priority" value={stats.urgent} note="Urgent or high" tone="rose"/></div>}</SectionCard></section>:null}
  <SectionCard title={tab==="overview"?"Recent Registry Activity":tabs.find(x=>x.key===tab)?.label+" Register"} eyebrow="Operational records"><div className="mb-4 grid gap-3 md:grid-cols-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search reference, subject, party..."/><select value={department} onChange={e=>setDepartment(e.target.value)}><option value="all">All departments</option>{departments.map(v=><option key={v}>{v}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map(v=><option key={v}>{v}</option>)}</select></div>
   {filtered.length===0?<EmptyState title={loading?"Loading registry records":"No registry records found"} description="No authorised record matches this workspace and filter."/>:<div className="overflow-x-auto rounded-xl border border-slate-200"><table className="min-w-full text-sm"><thead className="bg-slate-100"><tr>{["Reference","Subject / Party","Department","Direction","Priority","Status","Date"].map(h=><th key={h} className="px-4 py-3 text-left font-black text-slate-700">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 bg-white">{filtered.slice(0,tab==="overview"?12:500).map(r=><tr key={r.id} className="hover:bg-slate-50"><td className="px-4 py-4 font-black">{r.referenceNo}</td><td className="px-4 py-4"><div className="font-bold text-slate-900">{r.subject}</div><div className="mt-1 text-xs font-semibold text-slate-500">{r.direction.toLowerCase()==="incoming"?r.sender:r.recipient}</div></td><td className="px-4 py-4 font-semibold text-slate-600">{r.department}</td><td className="px-4 py-4"><StatusBadge tone="cyan">{r.direction}</StatusBadge></td><td className="px-4 py-4"><StatusBadge tone={/urgent|high/i.test(r.priority)?"rose":"slate"}>{r.priority}</StatusBadge></td><td className="px-4 py-4"><StatusBadge tone={badgeTone(r.status)}>{r.status}</StatusBadge></td><td className="px-4 py-4 font-semibold text-slate-500">{dateText(r.createdAt)}</td></tr>)}</tbody></table></div>}
  </SectionCard>
 </div></EnterpriseShell>
}
function Metric({label,value,total}:{label:string;value:number;total:number}){const width=Math.min(100,value/total*100);return <div><div className="mb-2 flex justify-between text-sm font-black text-slate-700"><span>{label}</span><span>{value.toLocaleString()}</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-700" style={{width:`${width}%`}}/></div></div>}
