"use client";

import { useMemo, useState } from "react";
import {
  Activity, AlertTriangle, BarChart3, BellRing, CalendarDays, CheckCircle2, ClipboardList,
  Clock3, FileBarChart, Landmark, Printer, RefreshCw, Scale, ShieldAlert, ShieldCheck,
  TrendingUp, UsersRound, WalletCards,
} from "lucide-react";
import { ExecButton, ExecEmpty, ExecHero, ExecLink, ExecSection, ExecStat, MiniBar } from "./ExecutiveUI";
import { dateOf, dateTime, numberOf, text, useExecutiveData, type Row } from "./useExecutiveData";

export type ExecutiveModule = "dashboard"|"requests"|"finance"|"hr"|"registry"|"audit"|"analytics"|"calendar"|"meetings"|"notifications"|"reports";

const configs: Record<ExecutiveModule,{eyebrow:string;title:string;description:string}> = {
  dashboard:{eyebrow:"Executive Intelligence",title:"Executive Command Centre",description:"Live institutional oversight across Requests, Finance, Human Resources, Registry, Audit, attendance and enterprise alerts."},
  requests:{eyebrow:"Workflow Oversight",title:"Executive Requests Intelligence",description:"Monitor volumes, pending decisions, approval stages, ageing requests and institutional processing pressure."},
  finance:{eyebrow:"Authorized Executive View",title:"Executive Finance Intelligence",description:"High-level voucher and transaction oversight for authorized executive roles without replacing Finance operational controls."},
  hr:{eyebrow:"People & Workforce",title:"Executive HR Intelligence",description:"Monitor HR workload, leave activity, seminar participation, departmental KPI records and workforce service delivery."},
  registry:{eyebrow:"Records & Correspondence",title:"Executive Registry Intelligence",description:"Track correspondence, open registry work, movement status and records requiring executive attention."},
  audit:{eyebrow:"Assurance & Governance",title:"Executive Audit Intelligence",description:"Review significant activity, risk signals, role switches and compliance evidence across the platform."},
  analytics:{eyebrow:"Enterprise Performance",title:"Executive Analytics Centre",description:"Consolidated performance indicators, workload ratios and trend signals drawn from authorized enterprise data."},
  calendar:{eyebrow:"Institutional Schedule",title:"Executive Calendar",description:"A consolidated view of leave periods, seminars, workflow deadlines and upcoming institutional activities."},
  meetings:{eyebrow:"Governance & Follow-up",title:"Executive Meetings Centre",description:"Track scheduled governance activities, seminar sessions and action-oriented institutional events."},
  notifications:{eyebrow:"Priority Communications",title:"Executive Notification Centre",description:"Review unread updates, priority workflow alerts and recent institutional notifications in one workspace."},
  reports:{eyebrow:"Official Executive Output",title:"Executive Reports Centre",description:"Generate an executive summary from live authorized data and print it in a clean management-ready format."},
};

function statusTone(status:string){ if(/rejected|failed|overdue|critical/i.test(status)) return "rose" as const; if(/approved|completed|paid|closed|filed/i.test(status)) return "emerald" as const; if(/pending|review|waiting|open/i.test(status)) return "amber" as const; return "blue" as const; }
function isToday(value:unknown){const d=dateOf(value);const n=new Date();return Boolean(d&&d.toDateString()===n.toDateString());}
function recent(rows:Row[],count=8){return rows.slice().sort((a,b)=>(dateOf(b.created_at)?.getTime()??0)-(dateOf(a.created_at)?.getTime()??0)).slice(0,count);}

export default function ExecutiveModulePage({ module }: { module: ExecutiveModule }) {
  const {data,metrics,loading,coverage,warning,refresh}=useExecutiveData();
  const [query,setQuery]=useState("");
  const config=configs[module];
  const requestRows=data.requests??[];

  const filteredRequests=useMemo(()=>requestRows.filter(r=>[r.request_no,r.title,r.status,r.current_stage].some(v=>text(v).toLowerCase().includes(query.toLowerCase()))),[requestRows,query]);

  const print=()=>window.print();

  return <div className="space-y-6">
    <ExecHero eyebrow={config.eyebrow} title={config.title} description={config.description}>
      <ExecButton onClick={()=>void refresh()} tone="cyan" disabled={loading}><RefreshCw className="h-4 w-4" />{loading?"Refreshing...":"Refresh Live Data"}</ExecButton>
      {module==="reports" && <ExecButton onClick={print} tone="emerald"><Printer className="h-4 w-4" />Print Executive Report</ExecButton>}
      {module!=="dashboard" && <ExecLink href="/executive" tone="slate">Command Centre</ExecLink>}
    </ExecHero>

    {warning && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900">{warning}</div>}

    {module==="dashboard" && <Dashboard data={data} metrics={metrics} coverage={coverage} />}
    {module==="requests" && <Requests rows={filteredRequests} query={query} setQuery={setQuery} metrics={metrics} />}
    {module==="finance" && <Finance data={data} metrics={metrics} />}
    {module==="hr" && <HR data={data} metrics={metrics} />}
    {module==="registry" && <Registry rows={data.registry??[]} />}
    {module==="audit" && <Audit data={data} />}
    {module==="analytics" && <Analytics data={data} metrics={metrics} coverage={coverage} />}
    {module==="calendar" && <Calendar data={data} />}
    {module==="meetings" && <Meetings data={data} />}
    {module==="notifications" && <Notifications rows={data.notifications??[]} />}
    {module==="reports" && <Reports data={data} metrics={metrics} coverage={coverage} />}
  </div>;
}

function Dashboard({data,metrics,coverage}:{data:Record<string,Row[]>;metrics:any;coverage:number}){
  const departments=[
    ["Requests",metrics.pending,metrics.requests,"/executive/requests"],
    ["Finance",metrics.financePending,metrics.vouchers,"/executive/finance"],
    ["Human Resources",metrics.hrPending,(data.hrAssignments??[]).length,"/executive/hr"],
    ["Registry",metrics.registryOpen,(data.registry??[]).length,"/executive/registry"],
  ] as const;
  const feed=recent([...(data.requests??[]).map(r=>({...r,_module:"Requests"})),...(data.audit??[]).map(r=>({...r,_module:"Audit"})),...(data.notifications??[]).map(r=>({...r,_module:"Notifications"}))],10);
  return <>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <ExecStat label="Total Requests" value={metrics.requests} note="Authorized records in scope" icon={ClipboardList} tone="blue" />
      <ExecStat label="Pending Decisions" value={metrics.pending} note="Requests not yet closed" icon={Clock3} tone="amber" />
      <ExecStat label="HR Queue" value={metrics.hrPending} note="Open HR assignments" icon={UsersRound} tone="violet" />
      <ExecStat label="Registry Queue" value={metrics.registryOpen} note="Open correspondence" icon={FileBarChart} tone="cyan" />
      <ExecStat label="Finance Pending" value={metrics.financePending} note="Vouchers awaiting completion" icon={WalletCards} tone="rose" />
      <ExecStat label="Attendance" value={`${metrics.attendanceRate.toFixed(1)}%`} note="Captured seminar participation" icon={TrendingUp} tone="emerald" />
      <ExecStat label="Leave Today" value={metrics.leaveToday} note="Recorded staff on leave" icon={CalendarDays} tone="amber" />
      <ExecStat label="Audit Events" value={metrics.audit} note={`${coverage}% data-source coverage`} icon={ShieldCheck} tone="slate" />
    </section>
    <section className="grid gap-6 lg:grid-cols-2">
      <ExecSection title="Directorate Operating Status" eyebrow="Live Workload">
        <div className="grid gap-3">{departments.map(([name,pending,total,href])=><a key={name} href={href} className="rounded-2xl border border-slate-200 p-4 transition hover:border-cyan-300 hover:shadow-sm"><div className="flex items-center justify-between"><div><p className="font-black text-slate-950">{name}</p><p className="mt-1 text-xs font-semibold text-slate-500">{pending} pending from {total} records</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${pending>10?"bg-rose-100 text-rose-800":pending>0?"bg-amber-100 text-amber-800":"bg-emerald-100 text-emerald-800"}`}>{pending>10?"Pressure":pending>0?"Active":"Healthy"}</span></div></a>)}</div>
      </ExecSection>
      <ExecSection title="Executive Activity Feed" eyebrow="Latest Evidence">
        <div className="space-y-3">{feed.length?feed.map((r,i)=><div key={`${text(r.id)}-${i}`} className="rounded-2xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><p className="font-black text-slate-900">{text(r.title)||text(r.action)||text(r.request_no)||"Enterprise activity"}</p><span className="text-[10px] font-black uppercase text-blue-700">{text(r._module)}</span></div><p className="mt-1 text-xs font-semibold text-slate-500">{text(r.status)||text(r.message)||text(r.body)||text(r.details,"Recorded activity")}</p><p className="mt-2 text-[11px] font-bold text-slate-400">{dateTime(r.created_at)}</p></div>):<ExecEmpty title="No recent activity" description="New enterprise activity will appear here." />}</div>
      </ExecSection>
    </section>
  </>;
}

function Requests({rows,query,setQuery,metrics}:{rows:Row[];query:string;setQuery:(v:string)=>void;metrics:any}){
  const stageCounts=Object.entries(rows.reduce<Record<string,number>>((a,r)=>{const k=text(r.current_stage,"Unassigned");a[k]=(a[k]??0)+1;return a;},{})).sort((a,b)=>b[1]-a[1]).slice(0,6);
  return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><ExecStat label="Requests" value={metrics.requests} note="Total authorized records" icon={ClipboardList}/><ExecStat label="Pending" value={metrics.pending} note="Awaiting workflow completion" icon={Clock3} tone="amber"/><ExecStat label="Approved" value={metrics.approved} note="Approved or completed" icon={CheckCircle2} tone="emerald"/><ExecStat label="Today" value={rows.filter(r=>isToday(r.created_at)).length} note="Submitted today" icon={Activity} tone="cyan"/></section><section className="grid gap-6 lg:grid-cols-[1fr_1.6fr]"><ExecSection title="Stage Distribution" eyebrow="Bottleneck Monitor"><div className="space-y-4">{stageCounts.map(([name,count])=><MiniBar key={name} label={`${name} (${count})`} value={rows.length?count/rows.length*100:0}/>)}</div></ExecSection><ExecSection title="Request Register" eyebrow="Executive Queue" action={<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search requests..." className="min-h-11 rounded-xl border border-slate-300 px-4 text-sm font-semibold"/>}><div className="space-y-3">{rows.slice(0,30).map(r=><a href={`/requests/${text(r.id)}`} key={text(r.id)} className="block rounded-2xl border border-slate-200 p-4 hover:border-blue-300"><div className="flex flex-col gap-2 sm:flex-row sm:justify-between"><div><p className="font-black text-slate-950">{text(r.request_no,"Request")} · {text(r.title,"Untitled")}</p><p className="mt-1 text-xs font-semibold text-slate-500">{text(r.current_stage,"Unassigned")} · {dateTime(r.created_at)}</p></div><span className={`h-fit rounded-full px-3 py-1 text-xs font-black ${statusTone(text(r.status))==="emerald"?"bg-emerald-100 text-emerald-800":statusTone(text(r.status))==="rose"?"bg-rose-100 text-rose-800":"bg-amber-100 text-amber-800"}`}>{text(r.status,"Pending")}</span></div></a>)}{!rows.length&&<ExecEmpty title="No request found" description="No request matches the current search and active-role scope."/>}</div></ExecSection></section></>;
}

function Finance({data,metrics}:{data:Record<string,Row[]>;metrics:any}){const vouchers=data.vouchers??[];const tx=data.transactions??[];return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><ExecStat label="Vouchers" value={vouchers.length} note="Authorized voucher records" icon={WalletCards} tone="blue"/><ExecStat label="Pending Vouchers" value={metrics.financePending} note="Not yet paid or closed" icon={Clock3} tone="amber"/><ExecStat label="Transactions" value={tx.length} note="Visible transaction records" icon={Landmark} tone="cyan"/><ExecStat label="Recorded Value" value={`₦${Math.round(metrics.expenditure).toLocaleString()}`} note="Aggregate visible transaction amount" icon={TrendingUp} tone="emerald"/></section><ExecSection title="Recent Finance Activity" eyebrow="Executive Oversight"><div className="grid gap-3 lg:grid-cols-2">{recent([...vouchers.map(r=>({...r,_type:"Voucher"})),...tx.map(r=>({...r,_type:"Transaction"}))],20).map((r,i)=><div key={`${text(r.id)}-${i}`} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><p className="font-black text-slate-950">{text(r.voucher_no)||text(r.reference)||text(r.transaction_reference)||"Finance record"}</p><span className="text-xs font-black text-blue-700">{text(r._type)}</span></div><p className="mt-2 text-sm font-semibold text-slate-600">{text(r.status,"Recorded")} · ₦{Math.round(numberOf(r.amount||r.total_amount)).toLocaleString()}</p><p className="mt-2 text-xs font-bold text-slate-400">{dateTime(r.created_at)}</p></div>)}{!vouchers.length&&!tx.length&&<ExecEmpty title="Finance summary unavailable" description="The active role or RLS policy has not exposed executive finance records."/>}</div></ExecSection></>}

function HR({data,metrics}:{data:Record<string,Row[]>;metrics:any}){const assignments=data.hrAssignments??[];const leave=data.leave??[];const seminars=data.seminars??[];const kpis=data.kpis??[];return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><ExecStat label="HR Assignments" value={assignments.length} note={`${metrics.hrPending} currently open`} icon={UsersRound} tone="violet"/><ExecStat label="Leave Records" value={leave.length} note={`${metrics.leaveToday} active today`} icon={CalendarDays} tone="amber"/><ExecStat label="Seminar Sessions" value={seminars.length} note="Captured weekly sessions" icon={Activity} tone="cyan"/><ExecStat label="Department KPIs" value={kpis.length} note="Performance records" icon={BarChart3} tone="emerald"/></section><section className="grid gap-6 lg:grid-cols-2"><ExecSection title="HR Workload" eyebrow="Assignments"><div className="space-y-3">{recent(assignments,12).map(r=><div key={text(r.id)} className="rounded-2xl border border-slate-200 p-4"><p className="font-black text-slate-950">{text(r.section_key)||text(r.assignment_type)||"HR assignment"}</p><p className="mt-1 text-xs font-semibold text-slate-500">{text(r.status,"Assigned")} · {dateTime(r.created_at)}</p></div>)}{!assignments.length&&<ExecEmpty title="No HR assignment data" description="No assignment records are visible to the active role."/>}</div></ExecSection><ExecSection title="Workforce Signals" eyebrow="Participation & Performance"><div className="space-y-5"><MiniBar label="Seminar attendance" value={metrics.attendanceRate}/><MiniBar label="Open HR workload" value={assignments.length?metrics.hrPending/assignments.length*100:0}/><MiniBar label="KPI portfolio coverage" value={Math.min(100,kpis.length*5)}/></div></ExecSection></section></>}

function Registry({rows}:{rows:Row[]}){const open=rows.filter(r=>!/archived|closed|completed/i.test(text(r.status))).length;return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><ExecStat label="Correspondence" value={rows.length} note="Visible Registry records" icon={FileBarChart} tone="cyan"/><ExecStat label="Open" value={open} note="Awaiting closure or archive" icon={Clock3} tone="amber"/><ExecStat label="Incoming" value={rows.filter(r=>/incoming/i.test(text(r.direction)||text(r.correspondence_type))).length} note="Incoming records" icon={Activity} tone="blue"/><ExecStat label="Archived" value={rows.filter(r=>/archived/i.test(text(r.status))).length} note="Archived correspondence" icon={CheckCircle2} tone="emerald"/></section><ExecSection title="Registry Movement Register" eyebrow="Correspondence Intelligence"><div className="grid gap-3 lg:grid-cols-2">{recent(rows,24).map(r=><div key={text(r.id)} className="rounded-2xl border border-slate-200 p-4"><p className="font-black text-slate-950">{text(r.reference_no)||text(r.subject)||"Registry record"}</p><p className="mt-1 text-sm font-semibold text-slate-600">{text(r.direction)||text(r.correspondence_type)||"Correspondence"} · {text(r.status,"Open")}</p><p className="mt-2 text-xs font-bold text-slate-400">{dateTime(r.created_at)}</p></div>)}{!rows.length&&<ExecEmpty title="No Registry records" description="No Registry correspondence is visible to this active role."/>}</div></ExecSection></>}

function Audit({data}:{data:Record<string,Row[]>}){const rows=[...(data.audit??[]),...(data.roleSwitches??[]).map(r=>({...r,module:"Security",action:text(r.action,"Active role switched")}))];const risky=rows.filter(r=>/delete|reject|fail|unauthor|suspend|critical/i.test([r.action,r.details,r.status].map(text).join(" "))).length;return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><ExecStat label="Audit Evidence" value={rows.length} note="Consolidated visible events" icon={ShieldCheck} tone="slate"/><ExecStat label="Today" value={rows.filter(r=>isToday(r.created_at)).length} note="Recorded today" icon={Activity} tone="cyan"/><ExecStat label="Risk Signals" value={risky} note="Events requiring review" icon={ShieldAlert} tone="rose"/><ExecStat label="Role Switches" value={(data.roleSwitches??[]).length} note="Working-context changes" icon={UsersRound} tone="violet"/></section><ExecSection title="Executive Audit Timeline" eyebrow="Who Did What"><div className="space-y-3">{recent(rows,40).map((r,i)=><div key={`${text(r.id)}-${i}`} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-col gap-2 sm:flex-row sm:justify-between"><div><p className="font-black text-slate-950">{text(r.action)||text(r.event_type)||"Recorded action"}</p><p className="mt-1 text-sm font-semibold text-slate-600">{text(r.module)||text(r.source,"Enterprise")} · {text(r.actor_name)||text(r.user_id)||text(r.actor,"System user")}</p></div><span className={`h-fit rounded-full px-3 py-1 text-xs font-black ${/delete|reject|fail|unauthor|critical/i.test(text(r.action)+text(r.details))?"bg-rose-100 text-rose-800":"bg-blue-100 text-blue-800"}`}>{text(r.active_role)||text(r.role_name,"Audited")}</span></div><p className="mt-2 text-xs font-semibold text-slate-500">{text(r.details)||text(r.description)||text(r.new_value,"No additional narrative")}</p><p className="mt-2 text-[11px] font-bold text-slate-400">{dateTime(r.created_at)}</p></div>)}{!rows.length&&<ExecEmpty title="No audit evidence" description="No audit event is visible to this active role."/>}</div></ExecSection></>}

function Analytics({data,metrics,coverage}:{data:Record<string,Row[]>;metrics:any;coverage:number}){const completion=metrics.requests?metrics.approved/metrics.requests*100:0;const financeCompletion=metrics.vouchers?(metrics.vouchers-metrics.financePending)/metrics.vouchers*100:0;const hrTotal=(data.hrAssignments??[]).length;const hrCompletion=hrTotal?(hrTotal-metrics.hrPending)/hrTotal*100:0;return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><ExecStat label="Request Completion" value={`${completion.toFixed(1)}%`} note="Approved and closed requests" icon={TrendingUp} tone="emerald"/><ExecStat label="Finance Completion" value={`${financeCompletion.toFixed(1)}%`} note="Completed voucher portfolio" icon={Landmark} tone="blue"/><ExecStat label="HR Completion" value={`${hrCompletion.toFixed(1)}%`} note="Completed HR workload" icon={UsersRound} tone="violet"/><ExecStat label="Data Coverage" value={`${coverage}%`} note="Connected executive sources" icon={BarChart3} tone="cyan"/></section><ExecSection title="Enterprise Performance Portfolio" eyebrow="Normalized Indicators"><div className="grid gap-6 lg:grid-cols-2"><div className="space-y-5"><MiniBar label="Request completion" value={completion}/><MiniBar label="Finance completion" value={financeCompletion}/><MiniBar label="HR completion" value={hrCompletion}/><MiniBar label="Attendance participation" value={metrics.attendanceRate}/></div><div className="rounded-2xl bg-slate-950 p-6 text-white"><p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-300">Executive Interpretation</p><h3 className="mt-3 text-2xl font-black">{metrics.pending>20?"Workflow pressure requires intervention":"Institutional workflow is within manageable range"}</h3><p className="mt-3 text-sm font-semibold leading-7 text-slate-300">There are {metrics.pending} open requests, {metrics.financePending} pending vouchers and {metrics.hrPending} open HR assignments within the authorized data scope.</p></div></div></ExecSection></>}

function Calendar({data}:{data:Record<string,Row[]>}){const events=[...(data.leave??[]).map(r=>({...r,_kind:"Leave",_date:r.start_date,_title:text(r.leave_type,"Staff leave")})),...(data.seminars??[]).map(r=>({...r,_kind:"Seminar",_date:r.session_date||r.start_date,_title:text(r.topic,"Weekly Seminar")})),...(data.workflow??[]).map(r=>({...r,_kind:"Deadline",_date:r.due_at||r.deadline,_title:text(r.stage,"Workflow deadline")}))].filter(r=>dateOf(r._date)).sort((a,b)=>(dateOf(a._date)?.getTime()??0)-(dateOf(b._date)?.getTime()??0));return <><section className="grid gap-4 sm:grid-cols-3"><ExecStat label="Calendar Events" value={events.length} note="Consolidated institutional events" icon={CalendarDays} tone="blue"/><ExecStat label="Upcoming" value={events.filter(r=>(dateOf(r._date)?.getTime()??0)>=Date.now()).length} note="Future events" icon={Clock3} tone="amber"/><ExecStat label="Today" value={events.filter(r=>isToday(r._date)).length} note="Events occurring today" icon={Activity} tone="emerald"/></section><ExecSection title="Consolidated Executive Calendar" eyebrow="Leave, Seminar & Workflow"><div className="grid gap-3 md:grid-cols-2">{events.slice(0,40).map((r,i)=><div key={`${text(r.id)}-${i}`} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><p className="font-black text-slate-950">{text(r._title)}</p><span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-black text-blue-800">{text(r._kind)}</span></div><p className="mt-2 text-sm font-semibold text-slate-600">{dateTime(r._date)}</p></div>)}{!events.length&&<ExecEmpty title="No calendar events" description="Leave, seminar and workflow deadlines will appear here."/>}</div></ExecSection></>}

function Meetings({data}:{data:Record<string,Row[]>}){const seminars=data.seminars??[];const upcoming=seminars.filter(r=>(dateOf(r.session_date||r.start_date)?.getTime()??0)>=Date.now());return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><ExecStat label="Meeting Records" value={seminars.length} note="Seminar and governance sessions" icon={Scale} tone="violet"/><ExecStat label="Upcoming" value={upcoming.length} note="Scheduled future sessions" icon={CalendarDays} tone="cyan"/><ExecStat label="Completed" value={seminars.filter(r=>/closed|completed|verified/i.test(text(r.status))).length} note="Completed sessions" icon={CheckCircle2} tone="emerald"/><ExecStat label="Action Required" value={seminars.filter(r=>/draft|open|pending/i.test(text(r.status))).length} note="Sessions requiring follow-up" icon={AlertTriangle} tone="amber"/></section><ExecSection title="Governance Session Register" eyebrow="Agenda & Follow-up"><div className="grid gap-3 lg:grid-cols-2">{recent(seminars,30).map(r=><div key={text(r.id)} className="rounded-2xl border border-slate-200 p-4"><p className="font-black text-slate-950">{text(r.topic,"Wednesday Weekly Seminar")}</p><p className="mt-1 text-sm font-semibold text-slate-600">{text(r.facilitator,"Facilitator not recorded")} · {text(r.venue,"Venue not recorded")}</p><p className="mt-2 text-xs font-bold text-slate-400">{dateTime(r.session_date||r.start_date)} · {text(r.status,"Scheduled")}</p></div>)}{!seminars.length&&<ExecEmpty title="No meeting record" description="Governance meetings and seminar sessions will appear here."/>}</div></ExecSection></>}

function Notifications({rows}:{rows:Row[]}){const unread=rows.filter(r=>!Boolean(r.is_read));return <><section className="grid gap-4 sm:grid-cols-3"><ExecStat label="Notifications" value={rows.length} note="Recent authorized notifications" icon={BellRing} tone="blue"/><ExecStat label="Unread" value={unread.length} note="Awaiting attention" icon={AlertTriangle} tone="rose"/><ExecStat label="Today" value={rows.filter(r=>isToday(r.created_at)).length} note="Received today" icon={Activity} tone="cyan"/></section><ExecSection title="Executive Notification Inbox" eyebrow="Priority Updates"><div className="space-y-3">{recent(rows,50).map(r=><a key={text(r.id)} href={text(r.link,"/executive")} className={`block rounded-2xl border p-4 ${Boolean(r.is_read)?"border-slate-200 bg-white":"border-blue-200 bg-blue-50"}`}><div className="flex justify-between gap-3"><p className="font-black text-slate-950">{text(r.title,"Enterprise update")}</p><span className={`rounded-full px-3 py-1 text-xs font-black ${Boolean(r.is_read)?"bg-slate-100 text-slate-700":"bg-blue-700 text-white"}`}>{Boolean(r.is_read)?"Read":"Unread"}</span></div><p className="mt-2 text-sm font-semibold text-slate-600">{text(r.body)||text(r.message,"Open the related record for details.")}</p><p className="mt-2 text-xs font-bold text-slate-400">{dateTime(r.created_at)}</p></a>)}{!rows.length&&<ExecEmpty title="No notification" description="Executive notifications will appear here."/>}</div></ExecSection></>}

function Reports({data,metrics,coverage}:{data:Record<string,Row[]>;metrics:any;coverage:number}){return <div className="print:p-0"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4 print:grid-cols-4"><ExecStat label="Requests" value={metrics.requests} note={`${metrics.pending} pending`} icon={ClipboardList}/><ExecStat label="Vouchers" value={metrics.vouchers} note={`${metrics.financePending} pending`} icon={WalletCards} tone="amber"/><ExecStat label="HR Assignments" value={(data.hrAssignments??[]).length} note={`${metrics.hrPending} pending`} icon={UsersRound} tone="violet"/><ExecStat label="Coverage" value={`${coverage}%`} note="Executive data sources" icon={BarChart3} tone="cyan"/></section><ExecSection title="Executive Management Summary" eyebrow="Official Report"><div className="space-y-5 text-sm font-semibold leading-7 text-slate-700"><p>ReqGen currently exposes <strong>{metrics.requests}</strong> request records to this executive role. <strong>{metrics.pending}</strong> remain open, while <strong>{metrics.approved}</strong> are approved, completed, paid or filed.</p><p>The authorized finance scope contains <strong>{metrics.vouchers}</strong> payment vouchers and <strong>{(data.transactions??[]).length}</strong> transaction records. <strong>{metrics.financePending}</strong> vouchers remain pending.</p><p>Human Resources currently shows <strong>{(data.hrAssignments??[]).length}</strong> assignments, with <strong>{metrics.hrPending}</strong> open. Registry has <strong>{metrics.registryOpen}</strong> open correspondence records. Captured seminar attendance stands at <strong>{metrics.attendanceRate.toFixed(1)}%</strong>.</p><div className="grid gap-4 border-t border-slate-200 pt-6 sm:grid-cols-3"><div><p className="text-xs font-black uppercase text-slate-400">Prepared By</p><div className="mt-8 border-t border-slate-400 pt-2">Executive User</div></div><div><p className="text-xs font-black uppercase text-slate-400">Reviewed By</p><div className="mt-8 border-t border-slate-400 pt-2">Authorized Reviewer</div></div><div><p className="text-xs font-black uppercase text-slate-400">Date</p><div className="mt-8 border-t border-slate-400 pt-2">{new Date().toLocaleString("en-NG",{dateStyle:"long",timeStyle:"short",hour12:true})}</div></div></div></div></ExecSection></div>}
