"use client";
import { FormEvent,Suspense,useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { supabase } from "@/lib/supabaseClient";
import PublicAuthShell from "../components/PublicAuthShell";
function getAppOrigin(){return typeof window==="undefined"?"":window.location.origin}
function getResetRedirectUrl(){const appUrl=process.env.NEXT_PUBLIC_APP_URL||getAppOrigin();return `${appUrl.replace(/\/$/,"")}/reset-password`}
function cleanEmail(email:string){return email.trim().toLowerCase()}
function Content(){const sp=useSearchParams();const [email,setEmail]=useState("");const [sending,setSending]=useState(false);const [sent,setSent]=useState(false);const [msg,setMsg]=useState<string|null>(null);const [err,setErr]=useState<string|null>(null);const valid=useMemo(()=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(cleanEmail(email)),[email]);useEffect(()=>{const v=sp.get("email");if(v)setEmail(cleanEmail(v))},[sp]);async function submit(e:FormEvent){e.preventDefault();setMsg(null);setErr(null);const final=cleanEmail(email);if(!final)return setErr("Please enter your registered email address.");if(!valid)return setErr("Please enter a valid email address.");setSending(true);const {error}=await supabase.auth.resetPasswordForEmail(final,{redirectTo:getResetRedirectUrl()});setSending(false);if(error)return setErr(error.message);setSent(true);setMsg("Password reset email sent. Check your inbox and spam folder for the secure reset link.")}
return <PublicAuthShell title="Forgot Password" subtitle="Recover access to your ReqGen account securely">{err?<div className="auth-message error">{err}</div>:null}{msg?<div className="auth-message success">{msg}</div>:null}{!sent?<form onSubmit={submit}><div className="auth-field"><label>Email Address</label><div><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Enter your registered email" autoComplete="email"/></div></div><button className="auth-primary" disabled={sending||!valid}>{sending?"Sending reset link...":"Send Password Reset Link"}</button></form>:<div className="auth-next"><strong>Next Step</strong><p>Open the secure email link to set a new password. Complete 2FA verification where required.</p><button type="button" className="auth-secondary" onClick={()=>{setSent(false);setMsg(null)}}>Send Again</button></div>}<div className="auth-small-links"><Link href="/login">Back to Login</Link></div></PublicAuthShell>}
export default function ForgotPasswordPage(){return <Suspense fallback={<PublicAuthShell title="Forgot Password" subtitle="Preparing secure password recovery"><p className="auth-loading">Loading...</p></PublicAuthShell>}><Content/></Suspense>}
