"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { supabase } from "@/lib/supabaseClient";
import HRAccessGuard from "@/app/components/hr/HRAccessGuard";
import { PrimaryButton, SectionCard, StrategicHero, StrategicNavigation, StrategicShell, TextInput } from "@/app/components/hr/HRStrategicUI";

type Settings = { seminar_start: string; seminar_end: string; late_after: string; very_late_after: string; assignment_expiry_days: string; retention_years: string; kpi_cycle_year: string; assessment_weight: string };
const defaults: Settings = { seminar_start: "10:00", seminar_end: "12:00", late_after: "10:05", very_late_after: "10:30", assignment_expiry_days: "30", retention_years: "7", kpi_cycle_year: String(new Date().getFullYear()), assessment_weight: "40" };
export default function HRSettingsPage() {
  const [settings, setSettings] = useState<Settings>(defaults); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { const { data } = await supabase.from("hr_policy_settings").select("setting_key,setting_value"); if (data) { const next = { ...defaults }; data.forEach((row) => { if (row.setting_key in next) (next as Record<string, string>)[row.setting_key] = String(row.setting_value); }); setSettings(next); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(null); const rows = Object.entries(settings).map(([setting_key, setting_value]) => ({ setting_key, setting_value })); const { error } = await supabase.from("hr_policy_settings").upsert(rows, { onConflict: "setting_key" }); setMessage(error ? error.message : "HR policy settings saved successfully."); setSaving(false); }
  const set = (key: keyof Settings) => (value: string) => setSettings((current) => ({ ...current, [key]: value }));
  return <HRAccessGuard bossOnly><StrategicShell><StrategicHero eyebrow="HR Policy & Configuration" title="HR Settings Centre" description="Manage official HR operational parameters, seminar timing, assignment deadlines, retention rules, KPI cycles and assessment weightings." /><StrategicNavigation />{message ? <div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm font-bold text-blue-900">{message}</div> : null}<SectionCard title="HR Policy Parameters" eyebrow="Controlled Configuration"><form onSubmit={save} className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><TextInput label="Seminar start" type="time" value={settings.seminar_start} onChange={set("seminar_start")} /><TextInput label="Seminar end" type="time" value={settings.seminar_end} onChange={set("seminar_end")} /><TextInput label="Late after" type="time" value={settings.late_after} onChange={set("late_after")} /><TextInput label="Very late after" type="time" value={settings.very_late_after} onChange={set("very_late_after")} /><TextInput label="Default assignment expiry (days)" type="number" value={settings.assignment_expiry_days} onChange={set("assignment_expiry_days")} /><TextInput label="Personnel record retention (years)" type="number" value={settings.retention_years} onChange={set("retention_years")} /><TextInput label="Active KPI cycle year" type="number" value={settings.kpi_cycle_year} onChange={set("kpi_cycle_year")} /><TextInput label="360° assessment weight (%)" type="number" value={settings.assessment_weight} onChange={set("assessment_weight")} /><div className="md:col-span-2 xl:col-span-4"><PrimaryButton type="submit" tone="emerald" disabled={saving}>{saving ? "Saving Settings..." : "Save HR Settings"}</PrimaryButton></div></form></SectionCard></StrategicShell></HRAccessGuard>;
}
