"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, Search, ShieldCheck, UserRound, Workflow } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
import { HRAccessGuard, HRNavigation } from "@/app/components/hr";
import { HRAlert, HRBadge, HREmpty, HRHero, HRPageShell, HRPanel, HRRefreshButton, HRStatCard, formatDateTime, pretty } from "@/app/components/hr/HREnterprisePage";

type Audit={id:string;action:string;entity_type:string;entity_id:string|null;actor_id:string|null;details:Record<string,unknown>|null;created_at:string};type Profile={id:string;full_name:string|null;email:string|null};
export default function HRAuditPage(){const [rows,setRows]=useState<Audit[]>([]);const [profiles,setProfiles]=useState<Profile[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [search,setSearch]=useState("");const [action,setAction]=useState("all");
 const load=useCallback(async()=>{setLoading(true);const [a,p]=await Promise.all([supabase.from("hr_assignment_history").select("id,action,entity_type,entity_id,actor_id,details,created_at").order("created_at",{ascending:false}).limit(1000),supabase.from("profiles").select("id,full_name,email")]);setRows((a.data||[]) as Audit[]);setProfiles((p.data||[]) as Profile[]);setError(a.error?.message||p.error?.message||"");setLoading(false);},[]);useEffect(()=>{void load();const channel=supabase.channel("hr-audit-live").on("postgres_changes",{event:"*",schema:"public",table:"hr_assignment_history"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel);};},[load]);const pmap=useMemo(()=>new Map(profiles.map(p=>[p.id,p.full_name||p.email||p.id])),[profiles]);const actions=useMemo(()=>Array.from(new Set(rows.map(r=>r.action))).sort(),[rows]);const filtered=rows.filter(r=>(action==="all"||r.action===action)&&[r.action,r.entity_type,r.entity_id,pmap.get(r.actor_id||""),JSON.stringify(r.details||{})].join(" ").toLowerCase().includes(search.toLowerCase()));const today=new Date().toDateString();const todayCount=rows.filter(r=>new Date(r.created_at).toDateString()===today).length;const actors=new Set(rows.map(r=>r.actor_id).filter(Boolean)).size;const entities=new Set(rows.map(r=>r.entity_type)).size;
 return <HRAccessGuard bossOnly><HRPageShell><HRHero eyebrow="Immutable HR Accountability" title="HR Enterprise Audit Trail" description="A live chronological record of officer assignments, delegated authority, reviews, returns, approvals, filing actions and personnel-record movements." icon={ShieldCheck} tone="slate" action={<HRRefreshButton onClick={()=>void load()} loading={loading}/>}/><HRNavigation/>{error&&<HRAlert message={error}/>}<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><HRStatCard label="Audit Events" value={rows.length} note="Latest HR accountability records" icon={Activity} tone="slate"/><HRStatCard label="Today" value={todayCount} note="Events recorded today" icon={Workflow} tone="cyan"/><HRStatCard label="Actors" value={actors} note="Distinct users performing HR actions" icon={UserRound} tone="violet"/><HRStatCard label="Entity Types" value={entities} note="HR record categories represented" icon={ShieldCheck} tone="emerald"/></section><HRPanel title="HR Activity Register" eyebrow="Who Did What" action={<div className="flex flex-col gap-2 sm:flex-row"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search actions, users or records..." className="min-h-11 rounded-xl border border-slate-200 pl-10 pr-4 text-sm font-semibold"/></div><select value={action} onChange={e=>setAction(e.target.value)} className="min-h-11 rounded-xl border border-slate-200 px-4 text-sm font-bold"><option value="all">All actions</option>{actions.map(a=><option key={a} value={a}>{pretty(a)}</option>)}</select></div>}>{loading?<p className="py-12 text-center font-bold text-slate-500">Loading HR audit evidence...</p>:filtered.length===0?<HREmpty title="No audit event matches the selected filters"/>:<div className="grid gap-3">{filtered.map(r=><article key={r.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 transition hover:bg-white hover:shadow-md"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap gap-2"><HRBadge value={r.action} tone="blue"/><HRBadge value={r.entity_type} tone="violet"/></div><h3 className="mt-3 font-black text-slate-950">{pmap.get(r.actor_id||"")||"System Process"}</h3><p className="mt-1 text-sm font-semibold text-slate-500">{formatDateTime(r.created_at)} · Record {r.entity_id||"Not linked"}</p></div><details className="max-w-xl rounded-xl bg-slate-950 p-3 text-xs text-slate-200"><summary className="cursor-pointer font-black text-white">View event details</summary><pre className="mt-3 whitespace-pre-wrap break-words">{JSON.stringify(r.details||{},null,2)}</pre></details></div></article>)}</div>}</HRPanel></HRPageShell></HRAccessGuard>}
