export type AccessMode = "allow" | "deny" | "authenticated";

export type AccessMatrixRow = {
  route: string;
  label: string;
  admin: AccessMode;
  auditor: AccessMode;
  dg: AccessMode;
  account: AccessMode;
  accountofficer: AccessMode;
  hrboss: AccessMode;
  hrofficer: AccessMode;
  registry: AccessMode;
  staff: AccessMode;
};

export const ACCESS_MATRIX_ROLES = [
  "admin",
  "auditor",
  "dg",
  "account",
  "accountofficer",
  "hrboss",
  "hrofficer",
  "registry",
  "staff",
] as const;

export const ACCESS_MATRIX: AccessMatrixRow[] = [
  {
    route: "/dashboard",
    label: "Dashboard",
    admin: "authenticated",
    auditor: "authenticated",
    dg: "authenticated",
    account: "authenticated",
    accountofficer: "authenticated",
    hrboss: "authenticated",
    hrofficer: "authenticated",
    registry: "authenticated",
    staff: "authenticated",
  },
  {
    route: "/requests",
    label: "Requests",
    admin: "authenticated",
    auditor: "authenticated",
    dg: "authenticated",
    account: "authenticated",
    accountofficer: "authenticated",
    hrboss: "authenticated",
    hrofficer: "authenticated",
    registry: "authenticated",
    staff: "authenticated",
  },
  {
    route: "/approvals",
    label: "Approvals",
    admin: "authenticated",
    auditor: "authenticated",
    dg: "authenticated",
    account: "authenticated",
    accountofficer: "authenticated",
    hrboss: "authenticated",
    hrofficer: "authenticated",
    registry: "authenticated",
    staff: "authenticated",
  },
  {
    route: "/finance",
    label: "Finance Control Centre",
    admin: "allow",
    auditor: "allow",
    dg: "allow",
    account: "allow",
    accountofficer: "allow",
    hrboss: "deny",
    hrofficer: "deny",
    registry: "deny",
    staff: "deny",
  },
  {
    route: "/payment-vouchers",
    label: "Payment Voucher Centre",
    admin: "allow",
    auditor: "allow",
    dg: "allow",
    account: "allow",
    accountofficer: "allow",
    hrboss: "deny",
    hrofficer: "deny",
    registry: "deny",
    staff: "deny",
  },
  {
    route: "/hr",
    label: "HR Directorate",
    admin: "allow",
    auditor: "deny",
    dg: "deny",
    account: "deny",
    accountofficer: "deny",
    hrboss: "allow",
    hrofficer: "allow",
    registry: "deny",
    staff: "deny",
  },
  {
    route: "/registry",
    label: "Registry Desk",
    admin: "allow",
    auditor: "allow",
    dg: "deny",
    account: "deny",
    accountofficer: "deny",
    hrboss: "deny",
    hrofficer: "deny",
    registry: "allow",
    staff: "deny",
  },
  {
    route: "/reports",
    label: "Reports & Analytics",
    admin: "allow",
    auditor: "allow",
    dg: "allow",
    account: "deny",
    accountofficer: "allow",
    hrboss: "deny",
    hrofficer: "deny",
    registry: "deny",
    staff: "deny",
  },
  {
    route: "/audit-centre",
    label: "Audit Centre",
    admin: "allow",
    auditor: "allow",
    dg: "deny",
    account: "deny",
    accountofficer: "deny",
    hrboss: "deny",
    hrofficer: "deny",
    registry: "deny",
    staff: "deny",
  },
  {
    route: "/admin",
    label: "Administration Centre",
    admin: "allow",
    auditor: "deny",
    dg: "deny",
    account: "deny",
    accountofficer: "deny",
    hrboss: "deny",
    hrofficer: "deny",
    registry: "deny",
    staff: "deny",
  },
  {
    route: "/admin/security",
    label: "Admin Security Read-only Oversight",
    admin: "allow",
    auditor: "allow",
    dg: "deny",
    account: "deny",
    accountofficer: "deny",
    hrboss: "deny",
    hrofficer: "deny",
    registry: "deny",
    staff: "deny",
  },
  {
    route: "/admin/audit",
    label: "Administrative Audit",
    admin: "allow",
    auditor: "allow",
    dg: "deny",
    account: "deny",
    accountofficer: "deny",
    hrboss: "deny",
    hrofficer: "deny",
    registry: "deny",
    staff: "deny",
  },
  {
    route: "/workflow",
    label: "Workflow Intelligence",
    admin: "allow",
    auditor: "allow",
    dg: "allow",
    account: "deny",
    accountofficer: "deny",
    hrboss: "deny",
    hrofficer: "deny",
    registry: "deny",
    staff: "deny",
  },
];
