export type ApprovedMockupSpec = {
  route: string;
  section: string;
  type: string;
  title: string;
  description: string;
  sections: string[];
};

export const APPROVED_MOCKUP_SPECS: ApprovedMockupSpec[] = [
  { route: "/payment-vouchers/[id]", section: "payment-vouchers", type: "detail", title: "Payment Voucher Details", description: "Generate, review, sign, print and administer payment vouchers using the existing approved request and signatory workflows.", sections: ["Voucher Details", "Voucher Items", "Disbursement Details", "Voucher Actions", "Voucher History"] },
  { route: "/payment-vouchers/[id]/print", section: "payment-vouchers", type: "print", title: "Payment Voucher Print View", description: "Generate, review, sign, print and administer payment vouchers using the existing approved request and signatory workflows.", sections: ["Checked By", "Authorized By", "Received By", "Cheque Signed By", "Counter Signed By"] },
  { route: "/payment-vouchers", section: "payment-vouchers", type: "hybrid", title: "Payment Voucher Centre", description: "Generate, review, sign, print and administer payment vouchers using the existing approved request and signatory workflows.", sections: ["Requests Ready for Voucher", "Voucher Register", "Create Manual Payment Voucher", "Generate Payment Voucher", "Ready Requests"] },
  { route: "/payment-vouchers/reports", section: "payment-vouchers", type: "redirect", title: "Voucher Reports", description: "Generate, review, sign, print and administer payment vouchers using the existing approved request and signatory workflows.", sections: [] },
  { route: "/payment-vouchers/settings", section: "payment-vouchers", type: "settings", title: "Payment Voucher Settings", description: "Generate, review, sign, print and administer payment vouchers using the existing approved request and signatory workflows.", sections: ["PV Signatories Register", "Total Names", "Active", "Inactive", "Cheque Signers"] },
  { route: "/registry/archive", section: "registry", type: "dashboard", title: "Registry Archive Register", description: "Track correspondence movement, dispatch, collection, archive status and request movement using the existing Registry records.", sections: [] },
  { route: "/registry/dispatch", section: "registry", type: "dashboard", title: "Dispatch & Collection Register", description: "Track correspondence movement, dispatch, collection, archive status and request movement using the existing Registry records.", sections: [] },
  { route: "/registry/incoming", section: "registry", type: "dashboard", title: "Incoming Register", description: "Track correspondence movement, dispatch, collection, archive status and request movement using the existing Registry records.", sections: [] },
  { route: "/registry/operations", section: "registry", type: "dashboard", title: "Registry Operations", description: "Track correspondence movement, dispatch, collection, archive status and request movement using the existing Registry records.", sections: [] },
  { route: "/registry/outgoing", section: "registry", type: "dashboard", title: "Outgoing Register", description: "Track correspondence movement, dispatch, collection, archive status and request movement using the existing Registry records.", sections: [] },
  { route: "/registry", section: "registry", type: "dashboard", title: "Registry Overview", description: "Track correspondence movement, dispatch, collection, archive status and request movement using the existing Registry records.", sections: ["Request Movement Intelligence", "Workflow Movement Pipeline", "Request Category Mix", "Department Movement Overview"] },
  { route: "/hr/analytics", section: "hr", type: "redirect", title: "Analytics", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: [] },
  { route: "/hr/archive", section: "hr", type: "dashboard", title: "HR Archive Governance Centre", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["Archive & Retention Register", "No archive record matches the current view", "Protected hold"] },
  { route: "/hr/assessments/annual-360", section: "hr", type: "redirect", title: "Annual 360", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: [] },
  { route: "/hr/assignments", section: "hr", type: "dashboard", title: "Officer Assignment & Delegation Centre", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["Grant Functional Authority", "Delegate a Specific HR Request", "Functional Authority Register", "No HR authority assigned", "Delegated Request Register"] },
  { route: "/hr/audit", section: "hr", type: "dashboard", title: "HR Audit & Compliance Centre", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["HR Activity Evidence Register", "No audit event matches the selected filters"] },
  { route: "/hr/capacity-building/departments", section: "hr", type: "redirect", title: "Departments", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: [] },
  { route: "/hr/capacity-building/staff", section: "hr", type: "redirect", title: "Staff", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: [] },
  { route: "/hr/compliance", section: "hr", type: "redirect", title: "Compliance", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: [] },
  { route: "/hr/department-kpi", section: "hr", type: "redirect", title: "Department Kpi", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: [] },
  { route: "/hr/filing", section: "hr", type: "dashboard", title: "HR Filing & Request Processing", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["HR Operational Register"] },
  { route: "/hr/leave", section: "hr", type: "dashboard", title: "Leave Operations Centre", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: [] },
  { route: "/hr/my-work", section: "hr", type: "dashboard", title: "My HR Work", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["My Assigned HR Functions", "No active HR function assigned", "Delegated Request Queue", "No delegated request matches this view"] },
  { route: "/hr/officer-performance", section: "hr", type: "redirect", title: "Officer Performance", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: [] },
  { route: "/hr/output", section: "hr", type: "redirect", title: "Output", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: [] },
  { route: "/hr", section: "hr", type: "dashboard", title: "HR Directorate Command Centre", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["HR request movement by stage", "HR Boss priority panel", "HR workload by department", "Recent HR-bound movement"] },
  { route: "/hr/registrar/analytics", section: "hr", type: "dashboard", title: "HR Executive Analytics", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["Performance Portfolio", "Management Insights", "Development Coverage", "KPI Attention", "Attendance Attention"] },
  { route: "/hr/registrar/assessments/annual-360", section: "hr", type: "hybrid", title: "Annual Staff 360° Assessment Centre", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["New Annual Assessment Cycle", "Assessment Cycles", "No assessment cycle created", "Assessment Assignment Monitor", "No assessor assignments yet"] },
  { route: "/hr/registrar/capacity-building/departments", section: "hr", type: "dashboard", title: "Department Capacity Building Centre", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: [] },
  { route: "/hr/registrar/capacity-building/staff", section: "hr", type: "dashboard", title: "Staff Capacity Building Centre", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: [] },
  { route: "/hr/registrar/compliance", section: "hr", type: "dashboard", title: "HR Compliance Centre", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["Compliance Timeline"] },
  { route: "/hr/registrar/department-kpi", section: "hr", type: "hybrid", title: "Department KPI Centre", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["New Department KPI", "Department KPI Register", "No KPI records configured"] },
  { route: "/hr/registrar/officer-performance", section: "hr", type: "dashboard", title: "HR Officer Performance & Workload", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["Officer Workload Register"] },
  { route: "/hr/registrar/output", section: "hr", type: "dashboard", title: "HR Print & Export Centre", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["Report Selection"] },
  { route: "/hr/registrar", section: "hr", type: "dashboard", title: "Registrar Centre", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["Custody & Classification Control", "Registry Activity", "Records Governance"] },
  { route: "/hr/registrar/reports", section: "hr", type: "dashboard", title: "HR Reports & Analytics Centre", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["Strategic HR Portfolio", "Management Attention", "No strategic HR records yet"] },
  { route: "/hr/registrar/settings", section: "hr", type: "settings", title: "HR Settings Centre", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["HR Policy Parameters"] },
  { route: "/hr/registrar/weekly-seminar", section: "hr", type: "hybrid", title: "Wednesday Weekly Seminar Centre", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["Seminar sessions", "Record staff attendance", "Staff attendance status", "Attendance by department", "Create Weekly Seminar"] },
  { route: "/hr/reports", section: "hr", type: "redirect", title: "Reports", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: [] },
  { route: "/hr/review", section: "hr", type: "dashboard", title: "HR Review & Decision Centre", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["HR Boss Review Queue", "Nothing is awaiting HR Boss review"] },
  { route: "/hr/settings", section: "hr", type: "redirect", title: "Settings", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: [] },
  { route: "/hr/staff", section: "hr", type: "dashboard", title: "Staff Files & Records Intelligence", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: ["Personnel File Register", "No staff files found"] },
  { route: "/hr/weekly-seminar", section: "hr", type: "redirect", title: "Weekly Seminar", description: "Operate the existing HR filing, assignments, staff records, leave, performance, capacity-building, compliance and reporting workflows.", sections: [] },
  { route: "/reports/enterprise-analytics", section: "reports", type: "dashboard", title: "Analytics Centre", description: "Review and export the consolidated operational reports already available to the authorised role.", sections: ["Operational Portfolio", "Performance Intelligence"] },
  { route: "/reports", section: "reports", type: "dashboard", title: "Reports Centre", description: "Review and export the consolidated operational reports already available to the authorised role.", sections: ["INSTITUTIONAL REPORT CONTROLS", "REPORT LOADING ERROR", "DATA SOURCE STATUS", "EXECUTIVE OVERVIEW & DECISION INSIGHTS", "REQUESTS & WORKFLOW PERFORMANCE"] },
  { route: "/audit-centre", section: "audit-centre", type: "dashboard", title: "Audit & Activity Centre", description: "Review recorded ReqGen audit activity, module events, risk levels and audit coverage.", sections: ["Live Activity Intelligence", "Audit Coverage", "Activity Register"] },
  { route: "/workflow", section: "workflow", type: "hybrid", title: "Workflow Intelligence Centre", description: "Review and maintain the existing workflow routing rules and SLA monitoring records.", sections: ["Create Workflow Rule", "Routing Rules", "No workflow rules", "SLA Monitoring", "No SLA events"] },
  { route: "/staff/attendance", section: "staff", type: "dashboard", title: "My Attendance", description: "Use the existing staff self-service functions for requests, leave, attendance, training, performance, notifications and downloads.", sections: ["Current Week", "Average Check In", "HR Verification", "Attendance History", "Present"] },
  { route: "/staff/downloads", section: "staff", type: "dashboard", title: "My Downloads", description: "Use the existing staff self-service functions for requests, leave, attendance, training, performance, notifications and downloads.", sections: ["Available Documents"] },
  { route: "/staff/leave/new", section: "staff", type: "form", title: "New Leave Application", description: "Use the existing staff self-service functions for requests, leave, attendance, training, performance, notifications and downloads.", sections: ["Leave Information", "Before You Submit"] },
  { route: "/staff/leave", section: "staff", type: "dashboard", title: "My Leave", description: "Use the existing staff self-service functions for requests, leave, attendance, training, performance, notifications and downloads.", sections: ["Leave Centre", "Current Leave", "Next Eligibility", "Last Leave", "Leave History"] },
  { route: "/staff/notifications", section: "staff", type: "dashboard", title: "My Notifications", description: "Use the existing staff self-service functions for requests, leave, attendance, training, performance, notifications and downloads.", sections: ["Unread", "Total", "Today", "System", "Official Request Approved"] },
  { route: "/staff", section: "staff", type: "hybrid", title: "Staff Overview", description: "Use the existing staff self-service functions for requests, leave, attendance, training, performance, notifications and downloads.", sections: ["Create Request", "Track Requests", "My Leave", "Attendance", "Downloads"] },
  { route: "/staff/performance", section: "staff", type: "dashboard", title: "My Performance", description: "Use the existing staff self-service functions for requests, leave, attendance, training, performance, notifications and downloads.", sections: ["KPI Achievement", "Department Rank", "Achievement Level", "Achievement Timeline", "Supervisor Remarks"] },
  { route: "/staff/profile", section: "staff", type: "redirect", title: "My Profile", description: "Use the existing staff self-service functions for requests, leave, attendance, training, performance, notifications and downloads.", sections: [] },
  { route: "/staff/requests", section: "staff", type: "dashboard", title: "My Requests", description: "Use the existing staff self-service functions for requests, leave, attendance, training, performance, notifications and downloads.", sections: ["No submitted request"] },
  { route: "/staff/training", section: "staff", type: "dashboard", title: "My Training", description: "Use the existing staff self-service functions for requests, leave, attendance, training, performance, notifications and downloads.", sections: ["Wednesday Weekly Seminar", "Completed", "Upcoming", "Certificates", "Learning Hours"] },
  { route: "/admin/access-audit", section: "admin", type: "dashboard", title: "Route Access Audit Matrix", description: "Administer the existing users, roles, departments, routing, security, settings, audit and system-readiness functions.", sections: [] },
  { route: "/admin/account-routing", section: "admin", type: "settings", title: "Department Account Routing", description: "Administer the existing users, roles, departments, routing, security, settings, audit and system-readiness functions.", sections: [] },
  { route: "/admin/audit", section: "admin", type: "dashboard", title: "Administrative Audit Trail", description: "Administer the existing users, roles, departments, routing, security, settings, audit and system-readiness functions.", sections: ["Audit Events"] },
  { route: "/admin/departments", section: "admin", type: "settings", title: "Departments", description: "Administer the existing users, roles, departments, routing, security, settings, audit and system-readiness functions.", sections: [] },
  { route: "/admin", section: "admin", type: "dashboard", title: "Admin Dashboard", description: "Administer the existing users, roles, departments, routing, security, settings, audit and system-readiness functions.", sections: ["Quick Multiple-Role Assignment", "Role Catalogue", "Global Routing Officers", "Department Routing", "Signature Readiness"] },
  { route: "/admin/release-readiness", section: "admin", type: "dashboard", title: "Release Readiness", description: "Administer the existing users, roles, departments, routing, security, settings, audit and system-readiness functions.", sections: ["Acceptance Checklist", "Automated Audit Commands", "360px phone layout", "390px phone layout", "768px tablet layout"] },
  { route: "/admin/roles", section: "admin", type: "hybrid", title: "Roles & Permissions", description: "Administer the existing users, roles, departments, routing, security, settings, audit and system-readiness functions.", sections: ["Role Register", "Total Roles", "Active", "Inactive", "System Roles"] },
  { route: "/admin/security", section: "admin", type: "dashboard", title: "Security Centre", description: "Administer the existing users, roles, departments, routing, security, settings, audit and system-readiness functions.", sections: ["Security, Backup & RLS Checklist", "Current User Security", "Security Checklist", "Backup Standard", "Sensitive Action Policy"] },
  { route: "/admin/settings", section: "admin", type: "settings", title: "System Settings", description: "Administer the existing users, roles, departments, routing, security, settings, audit and system-readiness functions.", sections: [] },
  { route: "/admin/system-health", section: "admin", type: "dashboard", title: "System Health", description: "Administer the existing users, roles, departments, routing, security, settings, audit and system-readiness functions.", sections: ["Data Source Health"] },
  { route: "/admin/users", section: "admin", type: "dashboard", title: "User Management", description: "Administer the existing users, roles, departments, routing, security, settings, audit and system-readiness functions.", sections: ["Total Users", "Assignments", "Staff", "Admin", "Auditor"] },
  { route: "/admin/workflow-test", section: "admin", type: "hybrid", title: "Workflow Test", description: "Administer the existing users, roles, departments, routing, security, settings, audit and system-readiness functions.", sections: ["Workflow Data Connections", "Create and submit request", "Routing and ownership", "Approval Operations Centre", "Realtime counters"] },
];

export function getApprovedMockupSpec(pathname: string): ApprovedMockupSpec | null {
  const exact = APPROVED_MOCKUP_SPECS.find((item) => item.route === pathname);
  if (exact) return exact;
  const detail = APPROVED_MOCKUP_SPECS.find((item) => item.route.includes("[id]") && new RegExp("^" + item.route.replace("[id]", "[^/]+") + "/?$").test(pathname));
  return detail ?? null;
}
