export type MockupRouteMeta = { section: string; type: string };

const ROUTES: Array<{ pattern: RegExp; meta: MockupRouteMeta }> = [
  { pattern: new RegExp("^/hr/registrar/capacity\-building/departments/?$"), meta: { section: "hr", type: "dashboard" } },
  { pattern: new RegExp("^/hr/registrar/capacity\-building/staff/?$"), meta: { section: "hr", type: "dashboard" } },
  { pattern: new RegExp("^/hr/registrar/assessments/annual\-360/?$"), meta: { section: "hr", type: "hybrid" } },
  { pattern: new RegExp("^/hr/capacity\-building/departments/?$"), meta: { section: "hr", type: "redirect" } },
  { pattern: new RegExp("^/hr/registrar/officer\-performance/?$"), meta: { section: "hr", type: "dashboard" } },
  { pattern: new RegExp("^/hr/registrar/department\-kpi/?$"), meta: { section: "hr", type: "hybrid" } },
  { pattern: new RegExp("^/hr/registrar/weekly\-seminar/?$"), meta: { section: "hr", type: "hybrid" } },
  { pattern: new RegExp("^/hr/capacity\-building/staff/?$"), meta: { section: "hr", type: "redirect" } },
  { pattern: new RegExp("^/hr/assessments/annual\-360/?$"), meta: { section: "hr", type: "redirect" } },
  { pattern: new RegExp("^/hr/registrar/compliance/?$"), meta: { section: "hr", type: "dashboard" } },
  { pattern: new RegExp("^/hr/registrar/analytics/?$"), meta: { section: "hr", type: "dashboard" } },
  { pattern: new RegExp("^/hr/registrar/settings/?$"), meta: { section: "hr", type: "settings" } },
  { pattern: new RegExp("^/hr/registrar/reports/?$"), meta: { section: "hr", type: "dashboard" } },
  { pattern: new RegExp("^/hr/registrar/output/?$"), meta: { section: "hr", type: "dashboard" } },
  { pattern: new RegExp("^/staff/leave/new/?$"), meta: { section: "staff", type: "form" } },
  { pattern: new RegExp("^/reports/enterprise\-analytics/?$"), meta: { section: "reports", type: "dashboard" } },
  { pattern: new RegExp("^/payment\-vouchers/settings/?$"), meta: { section: "payment-vouchers", type: "settings" } },
  { pattern: new RegExp("^/payment\-vouchers/reports/?$"), meta: { section: "payment-vouchers", type: "redirect" } },
  { pattern: new RegExp("^/admin/release\-readiness/?$"), meta: { section: "admin", type: "dashboard" } },
  { pattern: new RegExp("^/hr/officer\-performance/?$"), meta: { section: "hr", type: "redirect" } },
  { pattern: new RegExp("^/admin/account\-routing/?$"), meta: { section: "admin", type: "settings" } },
  { pattern: new RegExp("^/registry/operations/?$"), meta: { section: "registry", type: "dashboard" } },
  { pattern: new RegExp("^/staff/notifications/?$"), meta: { section: "staff", type: "dashboard" } },
  { pattern: new RegExp("^/admin/system\-health/?$"), meta: { section: "admin", type: "dashboard" } },
  { pattern: new RegExp("^/admin/workflow\-test/?$"), meta: { section: "admin", type: "hybrid" } },
  { pattern: new RegExp("^/admin/access\-audit/?$"), meta: { section: "admin", type: "dashboard" } },
  { pattern: new RegExp("^/registry/dispatch/?$"), meta: { section: "registry", type: "dashboard" } },
  { pattern: new RegExp("^/registry/incoming/?$"), meta: { section: "registry", type: "dashboard" } },
  { pattern: new RegExp("^/registry/outgoing/?$"), meta: { section: "registry", type: "dashboard" } },
  { pattern: new RegExp("^/hr/department\-kpi/?$"), meta: { section: "hr", type: "redirect" } },
  { pattern: new RegExp("^/hr/weekly\-seminar/?$"), meta: { section: "hr", type: "redirect" } },
  { pattern: new RegExp("^/staff/performance/?$"), meta: { section: "staff", type: "dashboard" } },
  { pattern: new RegExp("^/admin/departments/?$"), meta: { section: "admin", type: "settings" } },
  { pattern: new RegExp("^/registry/archive/?$"), meta: { section: "registry", type: "dashboard" } },
  { pattern: new RegExp("^/staff/attendance/?$"), meta: { section: "staff", type: "dashboard" } },
  { pattern: new RegExp("^/staff/downloads/?$"), meta: { section: "staff", type: "dashboard" } },
  { pattern: new RegExp("^/hr/assignments/?$"), meta: { section: "hr", type: "dashboard" } },
  { pattern: new RegExp("^/staff/requests/?$"), meta: { section: "staff", type: "dashboard" } },
  { pattern: new RegExp("^/staff/training/?$"), meta: { section: "staff", type: "dashboard" } },
  { pattern: new RegExp("^/admin/security/?$"), meta: { section: "admin", type: "dashboard" } },
  { pattern: new RegExp("^/admin/settings/?$"), meta: { section: "admin", type: "settings" } },
  { pattern: new RegExp("^/hr/compliance/?$"), meta: { section: "hr", type: "redirect" } },
  { pattern: new RegExp("^/staff/profile/?$"), meta: { section: "staff", type: "redirect" } },
  { pattern: new RegExp("^/hr/analytics/?$"), meta: { section: "hr", type: "redirect" } },
  { pattern: new RegExp("^/hr/registrar/?$"), meta: { section: "hr", type: "dashboard" } },
  { pattern: new RegExp("^/hr/settings/?$"), meta: { section: "hr", type: "redirect" } },
  { pattern: new RegExp("^/staff/leave/?$"), meta: { section: "staff", type: "dashboard" } },
  { pattern: new RegExp("^/admin/audit/?$"), meta: { section: "admin", type: "dashboard" } },
  { pattern: new RegExp("^/admin/roles/?$"), meta: { section: "admin", type: "hybrid" } },
  { pattern: new RegExp("^/admin/users/?$"), meta: { section: "admin", type: "dashboard" } },
  { pattern: new RegExp("^/hr/archive/?$"), meta: { section: "hr", type: "dashboard" } },
  { pattern: new RegExp("^/hr/my\-work/?$"), meta: { section: "hr", type: "dashboard" } },
  { pattern: new RegExp("^/hr/reports/?$"), meta: { section: "hr", type: "redirect" } },
  { pattern: new RegExp("^/hr/filing/?$"), meta: { section: "hr", type: "dashboard" } },
  { pattern: new RegExp("^/hr/output/?$"), meta: { section: "hr", type: "redirect" } },
  { pattern: new RegExp("^/hr/review/?$"), meta: { section: "hr", type: "dashboard" } },
  { pattern: new RegExp("^/hr/audit/?$"), meta: { section: "hr", type: "dashboard" } },
  { pattern: new RegExp("^/hr/leave/?$"), meta: { section: "hr", type: "dashboard" } },
  { pattern: new RegExp("^/hr/staff/?$"), meta: { section: "hr", type: "dashboard" } },
  { pattern: new RegExp("^/payment\-vouchers/?$"), meta: { section: "payment-vouchers", type: "hybrid" } },
  { pattern: new RegExp("^/audit\-centre/?$"), meta: { section: "audit-centre", type: "dashboard" } },
  { pattern: new RegExp("^/registry/?$"), meta: { section: "registry", type: "dashboard" } },
  { pattern: new RegExp("^/workflow/?$"), meta: { section: "workflow", type: "hybrid" } },
  { pattern: new RegExp("^/reports/?$"), meta: { section: "reports", type: "dashboard" } },
  { pattern: new RegExp("^/staff/?$"), meta: { section: "staff", type: "hybrid" } },
  { pattern: new RegExp("^/admin/?$"), meta: { section: "admin", type: "dashboard" } },
  { pattern: new RegExp("^/hr/?$"), meta: { section: "hr", type: "dashboard" } },
  { pattern: new RegExp("^/payment\-vouchers/[^/]+/print/?$"), meta: { section: "payment-vouchers", type: "print" } },
  { pattern: new RegExp("^/payment\-vouchers/[^/]+/?$"), meta: { section: "payment-vouchers", type: "detail" } },
];

export function getMockupRouteMeta(pathname: string): MockupRouteMeta | null {
  return ROUTES.find((item) => item.pattern.test(pathname))?.meta ?? null;
}
