"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { supabase } from "@/lib/supabaseClient";
import PublicAuthShell from "../components/PublicAuthShell";
type Dept={id:string;name:string};
export default function SignupPage(){ const router=useRouter(); const [departments,setDepartments]=useState<Dept[]>([]); const [loadingDepts,setLoadingDepts]=useState(true); const [fullName,setFullName]=useState(""); const [phone,setPhone]=useState(""); const [gender,setGender]=useState(""); const [deptId,setDeptId]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [confirmPassword,setConfirmPassword]=useState(""); const [msg,setMsg]=useState<string|null>(null); const [loading,setLoading]=useState(false);
useEffect(()=>{(async()=>{const {data,error}=await supabase.from("departments").select("id,name").eq("is_active",true).order("name",{ascending:true}); if(error)setMsg("Failed to load departments: "+error.message);else setDepartments((data||[]) as Dept[]);setLoadingDepts(false);})();},[]);
async function submit(e:React.FormEvent){e.preventDefault();setMsg(null);const clean=email.trim().toLowerCase();if(fullName.trim().length<3)return setMsg("Please enter your full name.");if(!gender)return setMsg("Please select gender.");if(!deptId)return setMsg("Please select department.");if(!clean.includes("@"))return setMsg("Please enter a valid email.");if(password.length<6)return setMsg("Password must be at least 6 characters.");if(confirmPassword!==password)return setMsg("Passwords do not match.");try{setLoading(true);const {error:signUpErr}=await supabase.auth.signUp({email:clean,password});if(signUpErr)throw new Error(signUpErr.message);const {data:signInData,error:signInErr}=await supabase.auth.signInWithPassword({email:clean,password});if(signInErr)throw new Error(signInErr.message);const {error:profileErr}=await supabase.from("profiles").insert({id:signInData.user.id,email:clean,full_name:fullName.trim(),phone:phone.trim()||null,dept_id:deptId,role:"Staff",gender,signature_url:null,is_active:true});if(profileErr)throw new Error(profileErr.message);router.push("/profile");}catch(e:unknown){setMsg(e instanceof Error?e.message:"Unable to create account");}finally{setLoading(false)}}
return <PublicAuthShell title="Create Account" subtitle="Register your official IET details to access ReqGen">
<div className="auth-tabs"><Link href="/login">Login</Link><span className="is-active">Create Account</span></div>{msg?<div className="auth-message">{msg}</div>:null}
<form onSubmit={submit} className="auth-form-grid"><div className="auth-field full"><label>Full Name</label><div><input value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="Your full name"/></div></div><div className="auth-field"><label>Phone</label><div><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="080..."/></div></div><div className="auth-field"><label>Gender</label><div><select value={gender} onChange={e=>setGender(e.target.value)}><option value="">Select gender</option><option>Male</option><option>Female</option></select></div></div><div className="auth-field full"><label>Department</label><div><select value={deptId} onChange={e=>setDeptId(e.target.value)} disabled={loadingDepts}><option value="">{loadingDepts?"Loading departments...":"Select department"}</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div></div><div className="auth-field full"><label>Email Address</label><div><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@domain.com"/></div></div><div className="auth-field"><label>Password</label><div><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 6 characters"/></div></div><div className="auth-field"><label>Confirm Password</label><div><input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder="Repeat password"/></div></div><button className="auth-primary full" disabled={loading}>{loading?"Creating account...":"Create Account"}</button></form>
</PublicAuthShell>}
