"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness, CheckCircle2, Clock3, RotateCcw, Send, TimerReset, WorkFlow } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
import { HRNavigation } from "@/app/components/hr";
import { HRAlert, HRBadge, HRButton, HREmpty, HRHero, HRPageShell, HRPanel, HRRefreshButton, HRStatCard, formatDate, pretty } from "@/app/components/hr/HREnterprisePage";

type WorkItem = { id:string; request_id:string; section_key:string; status:string; priority:string; due_at:string|null; assigned_at:string; submitted_at:string|null; boss_comment:string|null; officer_recommendation:string|null; requests?:{request_no?:string|null;title?:string|null;current_stage?:string|null;status?:string|null}|null };
const tabs = ["all","assigned","in_progress","returned","submitted","approved","completed"] as const;

export default function HRMyWorkPage(){
 const [items,setItems]=useState<WorkItem[]>([]); const [active,setActive]=useState<(typeof tabs)[number]>("all"); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(""); const [query,setQuery]=useState("");
 const load=useCallback(async()=>{setLoading(true);setMessage("");const {data:auth}=await supabase.auth.getUser();if(!auth.user){setMessage("Your session has expired.");setLoading(false);return;}const {data,error}=await supabase.from("hr_request_assignments").select("id,request_id,section_key,status,priority,due_at,assigned_at,submitted_at,boss_comment,officer_recommendation,requests(request_no,title,current_stage,status)").eq("officer_id",auth.user.id).order("assigned_at",{ascending:false});setItems((data||[]) as unknown as WorkItem[]);setMessage(error?.message||"");setLoading(false);},[]);
 useEffect(()=>{void load();},[load]);
 const shown=useMemo(()=>items.filter(x=>(active==="all"||x.status===active)&&[x.requests?.request_no,x.requests?.title,x.section_key,x.status,x.priority].join(" ").toLowerCase().includes(query.toLowerCase())),[items,active,query]);
 const overdue=items.filter(x=>x.due_at&&new Date(x.due_at)<new Date()&&!['completed','approved'].includes(x.status)).length;
 async function updateStatus(id:string,status:string){setMessage("");const patch:Record<string,unknown>={status};if(status==="in_progress")patch.started_at=new Date().toISOString();if(status==="submitted")patch.submitted_at=new Date().toISOString();const {error}=await supabase.from("hr_request_assignments").update(patch).eq("id",id);if(error)setMessage(error.message);else void load();}
 return <HRPageShell><HRHero eyebrow="Assigned HR Officer Workspace" title="My HR Work" description="A personal enterprise work queue showing every HR assignment delegated to your account, due dates, review feedback and submission status." icon={BriefcaseBusiness} tone="cyan" action={<HRRefreshButton onClick={()=>void load()} loading={loading}/>}/><HRNavigation/>{message&&<HRAlert message={message}/>}<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><HRStatCard label="Assigned Work" value={items.length} note="Total HR tasks allocated to you" icon={WorkFlow} tone="blue"/><HRStatCard label="In Progress" value={items.filter(x=>x.status==="in_progress").length} note="Tasks currently being processed" icon={TimerReset} tone="cyan"/><HRStatCard label="Submitted" value={items.filter(x=>x.status==="submitted").length} note="Awaiting HR Boss review" icon={Send} tone="violet"/><HRStatCard label="Overdue" value={overdue} note="Assignments beyond their due date" icon={Clock3} tone={overdue?"rose":"emerald"}/></section>
 <HRPanel title="Assigned Work Register" eyebrow="Officer Operations" action={<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search assigned work..." className="min-h-11 rounded-xl border border-slate-200 px-4 text-sm font-semibold outline-none focus:border-blue-500"/>}><div className="mb-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{tabs.map(tab=><button key={tab} onClick={()=>setActive(tab)} className={`rounded-xl px-3 py-2.5 text-xs font-black text-white shadow ${active===tab?"bg-slate-950 ring-4 ring-slate-200":"bg-cyan-600 hover:bg-cyan-700"}`}>{pretty(tab)} <span className="ml-1 rounded-full bg-white/20 px-2 py-1">{tab==="all"?items.length:items.filter(x=>x.status===tab).length}</span></button>)}</div>{loading?<p className="py-12 text-center font-bold text-slate-500">Loading assigned work...</p>:shown.length===0?<HREmpty title="No matching HR assignments"/>:<div className="grid gap-4">{shown.map(item=><article key={item.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-5 transition hover:bg-white hover:shadow-md"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap gap-2"><HRBadge value={item.section_key} tone="blue"/><HRBadge value={item.priority} tone={item.priority==="urgent"?"rose":"amber"}/><HRBadge value={item.status} tone={item.status==="completed"?"emerald":"slate"}/></div><h3 className="mt-3 text-lg font-black text-slate-950">{item.requests?.request_no||item.request_id} — {item.requests?.title||"HR-bound request"}</h3><p className="mt-2 text-sm font-semibold text-slate-600">Assigned {formatDate(item.assigned_at)} · Due {formatDate(item.due_at)} · Current stage {pretty(item.requests?.current_stage)}</p>{item.boss_comment&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-900">HR Boss feedback: {item.boss_comment}</p>}</div><div className="flex flex-wrap gap-2"><Link href={`/requests/${item.request_id}`} className="rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-black text-white shadow">Open Request</Link>{["assigned","returned"].includes(item.status)&&<HRButton onClick={()=>void updateStatus(item.id,"in_progress")} tone="amber"><RotateCcw className="h-4 w-4"/>Start Work</HRButton>}{item.status==="in_progress"&&<HRButton onClick={()=>void updateStatus(item.id,"submitted")} tone="violet"><Send className="h-4 w-4"/>Submit to HR Boss</HRButton>}{item.status==="completed"&&<HRBadge value="Completed" tone="emerald"/>}</div></div></article>)}</div>}</HRPanel></HRPageShell>;
}
