"use client";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabaseClient";
import { HRAccessGuard, HRNavigation } from "@/app/components/hr";

type Officer={id:string;full_name:string|null;email:string|null;role:string|null};
type Assignment={id:string;officer_id:string;section_key:string;permission_key:string;is_active:boolean};
type RequestRow={id:string;request_no:string|null;title:string|null;current_stage:string|null;status:string|null};
const sections=["leave","staff_filing","registrar","archive","weekly_seminar","staff_capacity_building","department_capacity_building","department_kpi","annual_360_assessment"];
const permissions=["view","process","recommend","submit_to_hr_boss","file","archive","manage"];
const pretty=(v:string)=>v.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function HRAssignmentsPage(){
 const [officers,setOfficers]=useState<Officer[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[requests,setRequests]=useState<RequestRow[]>([]);
 const [officerId,setOfficerId]=useState(""),[section,setSection]=useState(sections[0]),[permission,setPermission]=useState("process"),[requestId,setRequestId]=useState(""),[priority,setPriority]=useState("normal"),[dueAt,setDueAt]=useState(""),[instructions,setInstructions]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const [{data:p},{data:a},{data:r}]=await Promise.all([supabase.from("profiles").select("id,full_name,email,role").order("full_name"),supabase.from("hr_officer_assignments").select("id,officer_id,section_key,permission_key,is_active").order("created_at",{ascending:false}),supabase.from("requests").select("id,request_no,title,current_stage,status").order("created_at",{ascending:false}).limit(200)]);setOfficers((p||[]) as Officer[]);setAssignments((a||[]) as Assignment[]);setRequests((r||[]) as RequestRow[])}
 useEffect(()=>{queueMicrotask(()=>{void load();});},[]);const names=useMemo(()=>new Map(officers.map(o=>[o.id,o.full_name||o.email||o.id])),[officers]);
 async function assignRole(){if(!officerId)return;setBusy(true);const{data:u}=await supabase.auth.getUser();const{error}=await supabase.from("hr_officer_assignments").upsert({officer_id:officerId,section_key:section,permission_key:permission,is_active:true,assigned_by:u.user?.id},{onConflict:"officer_id,section_key,permission_key"});setMessage(error?.message||"Role assigned successfully.");setBusy(false);load()}
 async function assignRequest(){if(!officerId||!requestId)return;setBusy(true);const{data:u}=await supabase.auth.getUser();const{error}=await supabase.from("hr_request_assignments").upsert({request_id:requestId,officer_id:officerId,section_key:section,status:"assigned",priority,due_at:dueAt?new Date(dueAt).toISOString():null,instructions,assigned_by:u.user?.id},{onConflict:"request_id,officer_id,section_key"});setMessage(error?.message||"Request delegated successfully.");setBusy(false)}
 async function toggle(item:Assignment){await supabase.from("hr_officer_assignments").update({is_active:!item.is_active}).eq("id",item.id);load()}
 return <HRAccessGuard bossOnly><main className="min-h-screen bg-slate-50 px-4 py-8 lg:px-8"><div className="mx-auto max-w-7xl space-y-6"><section className="rounded-[2rem] bg-gradient-to-br from-violet-950 to-indigo-700 p-8 text-white shadow-xl"><p className="text-xs font-black uppercase tracking-[.25em] text-violet-200">HR Boss Control</p><h1 className="mt-3 text-3xl font-black lg:text-5xl">Officer Assignment Centre</h1><p className="mt-3 max-w-3xl font-semibold text-violet-100">Grant multiple HR functions, then delegate individual requests with priority, instructions and deadlines.</p></section><HRNavigation />{message&&<div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 font-bold text-blue-800">{message}</div>}
 <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">1. Assign HR Function</h2><div className="mt-4 grid gap-4 md:grid-cols-4"><select value={officerId} onChange={e=>setOfficerId(e.target.value)} className="rounded-xl border p-3 font-bold"><option value="">Select officer</option>{officers.map(o=><option key={o.id} value={o.id}>{o.full_name||o.email}</option>)}</select><select value={section} onChange={e=>setSection(e.target.value)} className="rounded-xl border p-3 font-bold">{sections.map(s=><option key={s} value={s}>{pretty(s)}</option>)}</select><select value={permission} onChange={e=>setPermission(e.target.value)} className="rounded-xl border p-3 font-bold">{permissions.map(p=><option key={p} value={p}>{pretty(p)}</option>)}</select><button disabled={busy||!officerId} onClick={assignRole} className="rounded-xl bg-violet-600 px-5 py-3 font-extrabold text-white disabled:opacity-50">Assign Function</button></div></section>
 <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">2. Delegate HR-bound Request</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-5"><select value={requestId} onChange={e=>setRequestId(e.target.value)} className="rounded-xl border p-3 font-bold xl:col-span-2"><option value="">Select request</option>{requests.map(r=><option key={r.id} value={r.id}>{r.request_no||r.id} — {r.title||"Untitled"}</option>)}</select><select value={officerId} onChange={e=>setOfficerId(e.target.value)} className="rounded-xl border p-3 font-bold"><option value="">Select officer</option>{officers.map(o=><option key={o.id} value={o.id}>{o.full_name||o.email}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)} className="rounded-xl border p-3 font-bold"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select><input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)} className="rounded-xl border p-3 font-bold"/><textarea value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Assignment instructions" className="min-h-24 rounded-xl border p-3 font-medium md:col-span-2 xl:col-span-4"/><button disabled={busy||!officerId||!requestId} onClick={assignRequest} className="rounded-xl bg-orange-600 px-5 py-3 font-extrabold text-white disabled:opacity-50">Delegate Request</button></div></section>
 <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-950 text-white"><tr><th className="p-4">Officer</th><th className="p-4">HR Section</th><th className="p-4">Permission</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody>{assignments.map(a=><tr key={a.id} className="border-t"><td className="p-4 font-bold">{names.get(a.officer_id)||a.officer_id}</td><td className="p-4">{pretty(a.section_key)}</td><td className="p-4">{pretty(a.permission_key)}</td><td className="p-4"><span className={`rounded-full px-3 py-1 font-bold ${a.is_active?"bg-emerald-100 text-emerald-700":"bg-slate-200 text-slate-600"}`}>{a.is_active?"Active":"Suspended"}</span></td><td className="p-4"><button onClick={()=>toggle(a)} className={`rounded-xl px-4 py-2 font-extrabold text-white ${a.is_active?"bg-red-600":"bg-emerald-600"}`}>{a.is_active?"Suspend":"Restore"}</button></td></tr>)}</tbody></table></div></section></div></main></HRAccessGuard>}
